import { test, expect } from "@playwright/test";

test("Mio: hypothesis, unequal times, independent retry and saved explanation", async ({ page }) => {
  await page.goto("/tasks/average-speed-segments");
  await page.getByRole("link", { name: "Разобраться в опыте с Мио" }).click();
  await expect(page.getByRole("img",{name:"Мио сомневается в своей гипотезе",exact:true})).toBeVisible();
  await page.getByRole("radio", { name: "Пока не знаю — хочу проверить" }).check();
  await page.getByRole("button", { name: "Проверить в опыте" }).click();
  await page.getByRole("button", { name: "Посчитать пройденный путь" }).click();
  await expect(page.getByRole("button", { name: "Объяснить результат" })).toBeDisabled();
  await page.getByRole("slider").focus();
  await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("slider")).toHaveValue("6");
  await page.getByRole("button", { name: "Посчитать пройденный путь" }).click();
  await expect(page.getByRole("status")).toContainText("4,4 м/с");
  await expect(page.getByLabel("Исправление гипотезы Мио")).toContainText("В этом опыте: 4,4 м/с");
  await page.getByRole("button", { name: "Объяснить результат" }).click();
  await page.getByRole("radio", { name: "Весь пройденный путь разделить на всё затраченное время" }).check();
  await page.getByRole("button", { name: "Решить самостоятельно" }).click();
  const answer = page.getByRole("textbox", { name: "Средняя путевая скорость, м/с" });
  await expect(answer).toHaveValue("");
  await answer.fill("4,5");
  await page.getByRole("button", { name: "Проверить ответ" }).click();
  await expect(page.getByRole("button", { name: "Подвести итог" })).toHaveCount(0);
  await expect(page.getByRole("status")).not.toContainText("4 м/с");
  await answer.fill("4,0");
  await page.getByRole("button", { name: "Проверить ответ" }).click();
  await expect(page.getByRole("status")).toContainText("после повторной попытки");
  await expect(page.getByRole("img", { name: "Мио радуется результату" })).toBeVisible();
  await page.getByRole("button", { name: "Подвести итог" }).click();
  await page.getByRole("textbox").fill("Время на участках разное, поэтому нужно разделить весь путь на всё время.");
  await page.getByRole("button", { name: "Сохранить моё объяснение" }).click();
  await page.getByRole("button", { name: "Скрыть Мио" }).click();
  await page.reload();
  await expect(page.getByRole("heading", { name: "Забери мысль с собой" })).toBeVisible();
  await expect(page.getByRole("textbox")).toHaveValue("Время на участках разное, поэтому нужно разделить весь путь на всё время.");
  await expect(page.getByRole("button", { name: "Показать Мио" })).toBeVisible();
  await expect(page.getByRole("status")).toContainText("Объяснение сохранено");
  await page.getByRole("link", { name: "Закрепить на новых задачах" }).click();
  await expect(page).toHaveURL(/\/practice\/family\/average-speed-segments$/);
});

test("Mio respects reduced motion and can be hidden", async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/practice/average-speed-lesson");
  const mio = page.getByRole("img", { name: "Мио сомневается в своей гипотезе" });
  await expect(mio).toBeVisible();
  await expect(mio).toHaveCSS("animation-name", "none");
  await page.getByRole("button", { name: "Скрыть Мио" }).click();
  await expect(mio).toHaveCount(0);
  await expect(page.getByRole("group", { name: "Как думаешь, время на каждом участке имеет значение?" })).toBeVisible();
  await page.getByRole("button",{name:"Показать Мио",exact:true}).click();
  await page.getByRole("radio",{name:"Пока не знаю — хочу проверить",exact:true}).check();
  await page.getByRole("button",{name:"Проверить в опыте",exact:true}).click();
  await page.getByRole("slider").focus();
  await page.keyboard.press("ArrowRight");
  await page.getByRole("button",{name:"Посчитать пройденный путь",exact:true}).click();
  await expect(page.getByLabel("Исправление гипотезы Мио").locator("svg path")).toHaveCSS("animation-name","none");
});
