import {test,expect} from "@playwright/test";
test("dynamometer reads forces, returns to zero, and keeps the independent answer",async({page})=>{
  await page.goto("/learn/force-and-dynamometer");
  const scene=page.getByRole("region",{name:"История и модель с Мио"});
  await expect(scene.locator("img")).toBeVisible();
  await expect(scene.getByRole("img",{name:/Динамометр от/})).toHaveAttribute("aria-label",/посередине между 1 и 2/);
  await expect(scene.getByRole("status")).toHaveCount(0);
  await scene.getByRole("button",{name:"Показать разбор шкалы",exact:true}).click();
  await expect(scene.getByRole("status")).toContainText("Показание: 1,5 Н");
  await scene.getByRole("button",{name:"Два одинаковых груза",exact:true}).click();
  await expect(scene.getByRole("status")).toHaveCount(0);
  await expect(scene.getByRole("img",{name:/Динамометр от/})).toHaveAttribute("aria-label",/на отметке 3 Н/);
  await scene.getByRole("button",{name:"Показать разбор шкалы",exact:true}).click();
  await expect(scene.getByRole("status")).toContainText("Показание: 3 Н");
  await scene.getByRole("button",{name:"Снять нагрузку",exact:true}).click();
  await expect(scene.getByRole("img",{name:/Динамометр от/})).toHaveAttribute("aria-label",/на нулевой отметке/);
  await page.getByRole("radio",{name:"1,5 кг",exact:true}).check();
  await page.getByRole("button",{name:"Проверить себя",exact:true}).click();
  await expect(page.getByRole("status").filter({hasText:"не килограмм"})).toBeVisible();
  await page.getByRole("radio",{name:"1,5 Н",exact:true}).check();
  await page.getByRole("button",{name:"Проверить себя",exact:true}).click();
  await page.reload();
  await expect(page.getByRole("radio",{name:"1,5 Н",exact:true})).toBeChecked();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.emulateMedia({reducedMotion:"reduce"});
  const motionProperties=await scene.locator("svg g[style]").evaluateAll(elements=>elements.map(element=>getComputedStyle(element).transitionProperty));
  expect(motionProperties.length).toBeGreaterThan(0);
  expect(motionProperties.every(property=>property==="none")).toBe(true);
});
