import type {TemplateId} from "../server/task-generator/generate.ts";

// Only link lessons that teach this family's actual skill. A broad topic route
// must not be used as a substitute for an explanation that does not exist yet.
const lessons:Partial<Record<TemplateId,{href:string;label:string}>>={
  "oscillation-frequency":{href:"/learn/mechanical-oscillations",label:"Учебник: период и частота колебаний"},
  "spring-oscillation-period":{href:"/learn/mechanical-spring-period",label:"Учебник: период груза на пружине"},
  "mathematical-pendulum-period":{href:"/learn/mathematical-pendulum",label:"Учебник: период груза на нити"},
  "lc-period":{href:"/learn/lc-oscillations",label:"Учебник: период колебаний в LC-контуре"},
  "ac-oscillogram-frequency":{href:"/learn/alternating-current",label:"Учебник: частота тока по двум максимумам"},
  "transformer-voltage-ratio":{href:"/learn/transformer",label:"Учебник: напряжение трансформатора"},
  "transmission-line-loss":{href:"/learn/electric-energy-transmission",label:"Учебник: нагрев линии передачи"},
  "em-wavelength-vacuum":{href:"/learn/electromagnetic-waves",label:"Учебник: длина радиоволны в вакууме"},
  "induced-emf-magnitude":{href:"/learn/electromagnetic-induction",label:"Учебник: изменение потока и ЭДС индукции"},
  "ampere-force-magnitude":{href:"/learn/magnetic-field-and-ampere-force",label:"Учебник: индукция поля и сила Ампера"},
  "lorentz-force-magnitude":{href:"/learn/lorentz-force-and-charge-motion",label:"Учебник: движение заряда в магнитном поле"},
  "metal-temperature-current":{href:"/learn/electric-current-in-metals",label:"Учебник: ток в металлах при нагреве"},
  "electrolyte-ion-transport":{href:"/learn/electric-current-in-electrolytes",label:"Учебник: ток в растворе соли и электролиз"},
  "gas-discharge-conditions":{href:"/learn/electric-current-in-gases",label:"Учебник: газовый разряд и плазма"},
  "semiconductor-carriers":{href:"/learn/electric-current-in-semiconductors",label:"Учебник: ток в полупроводнике"},
  "self-induction-emf":{href:"/learn/self-induction",label:"Учебник: ток, ЭДС и самоиндукция катушки"},
  "oscillation-energy":{href:"/learn/mechanical-oscillation-energy",label:"Учебник: энергия гармонических колебаний"},
  "resonance-frequency-match":{href:"/learn/mechanical-forced-oscillations",label:"Учебник: вынужденные колебания и резонанс"},
  "mechanical-wave-speed":{href:"/learn/mechanical-waves",label:"Учебник: как распространяется механическая волна"},
  "echo-ranging":{href:"/learn/sound-waves",label:"Учебник: звуковые волны и эхолот"},
  "archimedes-force":{href:"/learn/archimedes-force",label:"Учебник: почему вода выталкивает тело"},
  "ship-payload":{href:"/learn/ships-and-ballooning",label:"Учебник: ватерлиния и грузоподъёмность"},
  "relative-velocity-vectors":{href:"/learn/relative-motion",label:"Учебник: сложение скоростей"},
  "vt-slope":{href:"/learn/uniformly-accelerated-motion",label:"Учебник: наклон графика скорости"},
  "vt-area":{href:"/learn/uniformly-accelerated-motion",label:"Учебник: площадь под графиком скорости"},
  "rotation-frequency":{href:"/learn/circular-motion-kinematics",label:"Учебник: период и частота вращения"},
  "centripetal-acceleration":{href:"/learn/centripetal-acceleration",label:"Учебник: ускорение к центру окружности"},
  "average-speed-segments":{href:"/practice/average-speed-lesson",label:"Разобраться в опыте с Мио"},
  "average-speed-with-stop":{href:"/learn/uneven-motion",label:"Учебник: весь путь и всё время"},
  "uniform-coordinate-law":{href:"/learn/uniform-rectilinear-motion",label:"Учебник: координата через время"},
  "gravity-force":{href:"/learn/gravity-elasticity-weight",label:"Учебник: тяжесть, упругость и вес"},
  "gravitation-distance":{href:"/learn/universal-gravitation",label:"Учебник: закон всемирного тяготения"},
  "weight-lift":{href:"/learn/weight-weightlessness-overload",label:"Учебник: вес, невесомость и перегрузки"},
  "torque-balance":{href:"/learn/force-moment-and-equilibrium",label:"Учебник: момент силы и равновесие"},
  "movable-pulley":{href:"/learn/simple-machines-levers-pulleys",label:"Учебник: рычаги и блоки"},
  "impulse-momentum":{href:"/learn/momentum-and-systems",label:"Учебник: сила и изменение импульса"},
  "inelastic-collision-speed":{href:"/learn/momentum-conservation-and-reactive-motion",label:"Учебник: сохранение импульса при сцеплении"},
  "work-at-angle":{href:"/learn/work-and-power-vectors",label:"Учебник: работа силы под углом"},
  "resultant-force":{href:"/learn/resultant-force-and-friction",label:"Учебник: равнодействующая и трение"},
  "hydrostatic-pressure":{href:"/learn/hydrostatic-pressure",label:"Учебник: давление жидкости на глубине"},
  "work-force-distance":{href:"/learn/mechanical-work",label:"Учебник: механическая работа"},
  "mechanical-power":{href:"/learn/mechanical-power",label:"Учебник: механическая мощность"},
  "mechanical-efficiency":{href:"/learn/mechanical-efficiency",label:"Учебник: коэффициент полезного действия"},
  "kinetic-energy":{href:"/learn/kinetic-energy",label:"Учебник: кинетическая энергия"},
  "gravitational-potential-energy":{href:"/learn/potential-energy",label:"Учебник: потенциальная энергия"},
  "mechanical-energy-conservation":{href:"/learn/mechanical-energy-conservation",label:"Учебник: превращение и сохранение энергии"},
  "newton-second":{href:"/learn/newton-second-law",label:"Учебник: сила, масса и ускорение"},
  "friction-force":{href:"/learn/friction-and-medium-resistance",label:"Учебник: прижим и сила трения"},
  "free-fall":{href:"/learn/motion-under-gravity",label:"Учебник: движение под действием силы тяжести"},
  "projectile-components":{href:"/learn/projectile-motion-components",label:"Учебник: бросок под углом по двум осям"},
  "density-volume-ratio":{href:"/learn/density",label:"Учебник: масса, объём и плотность"},
  "contact-pressure":{href:"/learn/pressure",label:"Учебник: давление на опору"},
  "reflection-angle":{href:"/learn/reflection-of-light",label:"Учебник: закон отражения света"},
  "plane-mirror-separation":{href:"/learn/plane-mirror-image",label:"Учебник: изображение в плоском зеркале"},
  "shadow-and-penumbra":{href:"/learn/light-sources-and-shadows",label:"Учебник: источник света, тень и полутень"},
  "refraction-direction":{href:"/learn/refraction-of-light",label:"Учебник: направление преломлённого луча"},
  "lens-optical-power":{href:"/learn/lenses-and-optical-power",label:"Учебник: фокус и оптическая сила линзы"},
  "lens-image-properties":{href:"/learn/images-in-thin-lenses",label:"Учебник: построение изображения в линзе"},
  "vision-correction":{href:"/learn/vision-defects-and-correction",label:"Учебник: фокус, сетчатка и очки"},
  "ohm-law":{href:"/learn/electric-current-and-ohms-law",label:"Учебник: ток, напряжение и сопротивление"},
  "conductor-resistance":{href:"/learn/conductor-resistance",label:"Учебник: материал и размеры проводника"},
  "resistor-network":{href:"/learn/series-and-parallel-circuits",label:"Учебник: последовательная и параллельная цепи"},
  "electric-power":{href:"/learn/electric-work-and-power",label:"Учебник: работа и мощность тока"},
  "elementary-charge-count":{href:"/learn/electric-charge-and-atom",label:"Учебник: электризация и элементарный заряд"},
  "charge-sharing":{href:"/learn/charge-conservation-and-electrization",label:"Учебник: сохранение электрического заряда"},
  "coulomb-force":{href:"/learn/coulomb-law-point-charges",label:"Учебник: закон Кулона"},
  "electric-field-strength":{href:"/learn/electric-field-strength-and-superposition",label:"Учебник: напряжённость поля"},
  "electric-field-superposition":{href:"/learn/electric-field-strength-and-superposition",label:"Учебник: суперпозиция поля"},
  "electrostatic-field-work":{href:"/learn/electrostatic-field-work-and-potential",label:"Учебник: работа поля и потенциал"},
  "point-charge-potential":{href:"/learn/electrostatic-field-work-and-potential",label:"Учебник: потенциал точечного заряда"},
  "multi-source-potential":{href:"/learn/electrostatic-field-work-and-potential",label:"Учебник: потенциалы нескольких зарядов"},
  "uniform-field-voltage":{href:"/learn/electrostatic-potential-difference",label:"Учебник: разность потенциалов"},
  "parallel-plate-capacitance":{href:"/learn/capacitors-and-capacitance",label:"Учебник: почему меняется ёмкость конденсатора"},
  "capacitor-energy":{href:"/learn/capacitor-energy",label:"Учебник: энергия заряженного конденсатора"},
  "source-efficiency":{href:"/learn/full-circuit-ohms-law",label:"Учебник: КПД источника тока"},
  "magnetic-field-direction":{href:"/learn/magnetic-field-and-electromagnet",label:"Учебник: магнитное поле и электромагнит"},
  "heat-amount":{href:"/learn/heat-amount-and-balance",label:"Учебник: количество теплоты"},
  "molecule-count-from-mass":{href:"/learn/molecular-mass-and-amount",label:"Учебник: масса, моль и число молекул"},
  "particle-concentration":{href:"/learn/macro-micro-parameters-ideal-gas",label:"Учебник: концентрация и давление газа"},
  "molecular-kinetic-energy":{href:"/learn/thermal-equilibrium-and-temperature",label:"Учебник: температура и энергия молекул"},
  "ideal-gas-state":{href:"/learn/ideal-gas-state-equation",label:"Учебник: уравнение состояния газа"},
  "gas-state-ratio":{href:"/learn/ideal-gas-state-equation",label:"Учебник: сравнение двух состояний газа"},
  "ideal-gas-isoprocess":{href:"/learn/isoprocesses-ideal-gas",label:"Учебник: три изопроцесса"},
  "solid-structure-properties":{href:"/learn/solid-structure-and-properties",label:"Учебник: строение твёрдых тел"},
  "liquid-structure-properties":{href:"/learn/liquid-structure-and-properties",label:"Учебник: строение жидкостей"},
  "vapor-dynamic-equilibrium":{href:"/learn/evaporation-condensation-saturated-vapor",label:"Учебник: испарение и насыщенный пар"},
  "relative-humidity-pressure":{href:"/learn/air-humidity-and-dew-point",label:"Учебник: влажность воздуха и точка росы"},
  "monoatomic-internal-energy":{href:"/learn/thermodynamic-system-internal-energy",label:"Учебник: система и внутренняя энергия"},
  "isobaric-gas-work":{href:"/learn/gas-work-and-process-path",label:"Учебник: работа газа и путь процесса"},
  "first-law-energy-balance":{href:"/learn/first-law-thermodynamics",label:"Учебник: первый закон термодинамики"},
  "heat-engine-efficiency":{href:"/learn/heat-engine-cycle-and-efficiency",label:"Учебник: цикл теплового двигателя"},
  "heat-balance-simple":{href:"/learn/heat-amount-and-balance",label:"Учебник: тепловой баланс"},
  "fuel-combustion-heat":{href:"/learn/fuel-combustion",label:"Учебник: горение и энергия топлива"},
  "phase-change-heat":{href:"/learn/melting-and-crystallization",label:"Учебник: нагревание и плавление"},
  "vaporization-heat":{href:"/learn/evaporation-and-boiling",label:"Учебник: испарение и кипение"},
};
export function getFamilyLesson(family:TemplateId){return lessons[family]??null;}


