import type { HelpSectionId } from "./topic-help.ts";
import type { TopicId } from "./taxonomy.ts";

export type TaskLearningMetadata = {
  templateId: string;
  topicId: TopicId;
  helpSectionId: HelpSectionId;
  skillId: string;
  focusLabel: string;
  shortHint: string;
  misconceptionIds?: string[];
};

export type MisconceptionMetadata = {
  id: string;
  label: string;
  helpSectionId: HelpSectionId;
  shortHint: string;
};

export const misconceptionMetadataById: Record<string, MisconceptionMetadata> = {
  "oscillation-frequency-inverted": {
    id: "oscillation-frequency-inverted",
    label: "меняет местами период и частоту",
    helpSectionId: "oscillations",
    shortHint: "Период — секунды на один цикл, частота — циклы за секунду.",
  },
  "spring-period-missing-root": {
    id: "spring-period-missing-root",
    label: "не извлекает квадратный корень из отношения m/k",
    helpSectionId: "oscillations",
    shortHint: "В формуле $T=2\\pi\\sqrt{m/k}$ квадратный корень относится ко всему отношению.",
  },
  "spring-period-inverted-ratio": {
    id: "spring-period-inverted-ratio",
    label: "меняет местами массу и жёсткость",
    helpSectionId: "oscillations",
    shortHint: "Масса стоит в числителе, жёсткость — в знаменателе: $m/k$.",
  },
  "pendulum-period-missing-root": {
    id: "pendulum-period-missing-root",
    label: "не извлекает квадратный корень из отношения l/g",
    helpSectionId: "oscillations",
    shortHint: "В формуле $T=2\\pi\\sqrt{l/g}$ квадратный корень относится ко всему отношению.",
  },
  "pendulum-period-inverted-ratio": {
    id: "pendulum-period-inverted-ratio",
    label: "меняет местами длину нити и g",
    helpSectionId: "oscillations",
    shortHint: "Длина нити стоит в числителе, а g — в знаменателе: $l/g$.",
  },
  "oscillation-energy-confuses-forms": {
    id: "oscillation-energy-confuses-forms",
    label: "принимает энергию пружины за кинетическую",
    helpSectionId: "oscillations",
    shortHint: "При фиксированной полной энергии кинетическая равна разности полной энергии и энергии пружины.",
  },
  "mechanical-wave-speed-divides": {
    id: "mechanical-wave-speed-divides",
    label: "делит длину волны на частоту",
    helpSectionId: "oscillations",
    shortHint: "Длина волны — это путь за один период; за секунду источник создаёт несколько таких волн.",
  },
  "mechanical-wave-speed-inverts": {
    id: "mechanical-wave-speed-inverts",
    label: "переворачивает отношение частоты и длины волны",
    helpSectionId: "oscillations",
    shortHint: "Умножь длину волны на число колебаний источника за секунду: $v=\\lambda\\nu$.",
  },
  "mechanical-wave-speed-adds": {
    id: "mechanical-wave-speed-adds",
    label: "складывает величины вместо связи частоты и длины волны",
    helpSectionId: "oscillations",
    shortHint: "Скорость здесь задаёт произведение длины волны и частоты, а не их сумма.",
  },
  "echo-ranging-misses-return": {
    id: "echo-ranging-misses-return",
    label: "не учитывает обратный путь сигнала",
    helpSectionId: "oscillations",
    shortHint: "Отражённый сигнал возвращается к эхолоту, поэтому полное пройденное расстояние вдвое больше глубины.",
  },
  "echo-ranging-halves-twice": {
    id: "echo-ranging-halves-twice",
    label: "делит расстояние на два повторно",
    helpSectionId: "oscillations",
    shortHint: "Время уже относится к пути туда и обратно; раздели произведение скорости и времени только один раз.",
  },
  "echo-ranging-inverts-time": {
    id: "echo-ranging-inverts-time",
    label: "делит время на скорость вместо умножения",
    helpSectionId: "oscillations",
    shortHint: "Проверь единицы: м/с × с даёт метры, затем учти отражение сигнала.",
  },
  "resonance-frequency-match-half": {
    id: "resonance-frequency-match-half",
    label: "считает резонансом половину собственной частоты",
    helpSectionId: "oscillations",
    shortHint: "Сопоставь частоту толчков с собственной частотой системы, не дели её пополам.",
  },
  "resonance-frequency-match-double": {
    id: "resonance-frequency-match-double",
    label: "считает резонансом удвоенную собственную частоту",
    helpSectionId: "oscillations",
    shortHint: "Отклик усиливается, когда частоты близки, а не когда одна ровно вдвое больше.",
  },
  "resonance-frequency-match-period": {
    id: "resonance-frequency-match-period",
    label: "путает собственную частоту с периодом",
    helpSectionId: "oscillations",
    shortHint: "Частота измеряется в герцах, период — в секундах: это обратные величины.",
  },
  "isoprocess-proportionality": {
    id: "isoprocess-proportionality",
    label: "выбирает неверный вид пропорциональности",
    helpSectionId: "gas-isoprocesses",
    shortHint: "Сначала назови постоянный параметр и только затем выбирай отношение.",
  },
  "solid-structure-from-appearance": {
    id: "solid-structure-from-appearance",
    label: "определяет строение только по внешнему виду",
    helpSectionId: "solid-structure",
    shortHint: "Опирайся на направление свойств и характер плавления, а не только на блеск или форму образца.",
  },
  "liquid-bulk-surface-confusion": {
    id: "liquid-bulk-surface-confusion",
    label: "смешивает текучесть объёма и силы поверхностного слоя",
    helpSectionId: "liquid-structure",
    shortHint: "Сначала реши, говорится о перестройке соседей в объёме или о нескомпенсированных силах на поверхности.",
  },
  "vapor-equilibrium-means-stillness": {
    id: "vapor-equilibrium-means-stillness",
    label: "принимает динамическое равновесие за остановку молекул",
    helpSectionId: "vapor-equilibrium",
    shortHint: "Постоянный уровень означает равенство встречных потоков, а не прекращение переходов через поверхность.",
  },
  "relative-humidity-wrong-denominator": {
    id: "relative-humidity-wrong-denominator",
    label: "сравнивает влажность без учёта температуры насыщения",
    helpSectionId: "air-humidity",
    shortHint: "Используй давление или плотность насыщенного пара именно при температуре воздуха в условии.",
  },
  "internal-energy-missing-factor": {
    id: "internal-energy-missing-factor",
    label: "теряет множитель три вторых во внутренней энергии одноатомного газа",
    helpSectionId: "internal-energy-gas",
    shortHint: "Средняя энергия одной частицы равна 3kT/2, поэтому для ν моль сохраняется множитель 3/2.",
  },
  "gas-work-uses-final-volume": {
    id: "gas-work-uses-final-volume",
    label: "подставляет конечный объём вместо изменения объёма",
    helpSectionId: "gas-work",
    shortHint: "Сначала вычти начальный объём из конечного, затем умножь на давление.",
  },
  "first-law-adds-gas-work": {
    id: "first-law-adds-gas-work",
    label: "складывает полученное тепло с работой газа",
    helpSectionId: "first-law",
    shortHint: "Если A означает работу газа, вычти её из Q. При работе внешних сил знак будет противоположным.",
  },
  "heat-engine-uses-cooler-heat": {
    id: "heat-engine-uses-cooler-heat",
    label: "принимает теплоту холодильника за работу двигателя",
    helpSectionId: "heat-engine",
    shortHint: "Сначала вычти теплоту, отданную холодильнику: A₍ц₎ = Q₁ − |Q₂|.",
  },
  "molecular-energy-celsius": {
    id: "molecular-energy-celsius",
    label: "подставляет градусы Цельсия вместо кельвинов",
    helpSectionId: "molecular-kinetic-energy",
    shortHint: "Сначала переведи температуру: T = t + 273.",
  },
  "particle-concentration-volume-unit": {
    id: "particle-concentration-volume-unit",
    label: "не переводит литры в кубические метры",
    helpSectionId: "particle-concentration",
    shortHint: "Перед вычислением концентрации переведи объём: 1 л = 10⁻³ м³.",
  },
  "molecule-count-skips-molar-mass": {
    id: "molecule-count-skips-molar-mass",
    label: "умножает массу прямо на постоянную Авогадро",
    helpSectionId: "amount-of-substance",
    shortHint: "Постоянная Авогадро относится к одному молю: сначала раздели массу на молярную массу.",
  },
  "uniform-motion-coordinate-sign": {
    id: "uniform-motion-coordinate-sign",
    label: "теряет знак проекции скорости",
    helpSectionId: "uniform-motion-graphs",
    shortHint: "В x = x₀ + vₓt проекция vₓ отрицательна при движении против выбранной оси.",
  },
  "uniform-motion-graph-reading": {
    id: "uniform-motion-graph-reading",
    label: "читает график без проверки осей",
    helpSectionId: "uniform-motion-graphs",
    shortHint: "На s(t) наклон показывает скорость; на v(t) высота линии показывает скорость.",
  },
  "vt-area-not-final-speed": {
    id: "vt-area-not-final-speed",
    label: "читает скорость как путь",
    helpSectionId: "motion-graphs",
    shortHint: "На v(t) знаковая площадь даёт перемещение; путь — сумма модулей площадей.",
  },
  "slope-vs-area": {
    id: "slope-vs-area",
    label: "путает наклон и площадь",
    helpSectionId: "motion-graphs",
    shortHint: "Наклон v(t) даёт ускорение, а знаковая площадь — перемещение.",
  },
  "forgot-acceleration-term": {
    id: "forgot-acceleration-term",
    label: "теряет член ускорения",
    helpSectionId: "accelerated-motion",
    shortHint: "При постоянном ускорении путь содержит член at²/2.",
  },
  "average-speed-arithmetic-mean": {
    id: "average-speed-arithmetic-mean",
    label: "усредняет скорости без учета времени",
    helpSectionId: "average-speed",
    shortHint: "Средняя путевая скорость равна всему пути, делённому на всё время.",
  },
  "projectile-axis-components": {
    id: "projectile-axis-components",
    label: "смешивает движения по двум осям",
    helpSectionId: "accelerated-motion",
    shortHint: "По x скорость постоянна; время полёта и высоту сначала находит вертикальная компонента v₀ᵧ.",
  },
  "average-speed-omits-stop": {
    id: "average-speed-omits-stop",
    label: "не включает остановку во всё время",
    helpSectionId: "average-speed",
    shortHint: "Пока тело стоит, путь не растёт, но общее время движения продолжается.",
  },
  "speed-unit-conversion": {
    id: "speed-unit-conversion",
    label: "не переводит скорость и время к одним единицам",
    helpSectionId: "units-conversion",
    shortHint: "Перед расчетом пути переведи км/ч в м/с, а минуты в секунды.",
  },
  "length-unit-conversion-direction": {
    id: "length-unit-conversion-direction",
    label: "меняет число в неверном направлении при переводе длины",
    helpSectionId: "units-conversion",
    shortHint: "Из км в м число увеличивается; из дм, см и мм в м — уменьшается. Длина остаётся прежней.",
  },
  "graduated-scale-omits-base": {
    id: "graduated-scale-omits-base",
    label: "отсчитывает деления от нуля",
    helpSectionId: "graduated-scale",
    shortHint: "К пройденным делениям прибавь значение подписанной нижней отметки.",
  },
  "graduated-scale-counts-marks": {
    id: "graduated-scale-counts-marks",
    label: "считает отметки вместо промежутков",
    helpSectionId: "graduated-scale",
    shortHint: "Между двумя крайними штрихами число промежутков на единицу меньше числа штрихов.",
  },
  "graduated-scale-one-step-extra": {
    id: "graduated-scale-one-step-extra",
    label: "сдвигает мениск на одно деление",
    helpSectionId: "graduated-scale",
    shortHint: "Отсчитывай интервалы от подписанной отметки и остановись на делении мениска.",
  },
  "block-volume-omits-third-edge": {
    id: "block-volume-omits-third-edge",
    label: "умножает только два ребра и получает площадь",
    helpSectionId: "rectangular-block-volume",
    shortHint: "Произведение двух рёбер даёт площадь основания; для объёма умножь ещё на третье ребро.",
  },
  "block-volume-adds-height": {
    id: "block-volume-adds-height",
    label: "складывает площадь основания с высотой",
    helpSectionId: "rectangular-block-volume",
    shortHint: "Площадь в см² нельзя складывать с длиной в см. Умножь площадь основания на высоту.",
  },
  "block-volume-adds-edges": {
    id: "block-volume-adds-edges",
    label: "складывает три ребра вместо перемножения",
    helpSectionId: "rectangular-block-volume",
    shortHint: "Сумма длин остаётся длиной; объём прямоугольного бруска равен произведению трёх рёбер.",
  },
  "displacement-takes-final-reading": {
    id: "displacement-takes-final-reading",
    label: "принимает второе показание за объём тела",
    helpSectionId: "irregular-body-volume",
    shortHint: "Второе показание включает воду и тело; вычти начальный объём воды.",
  },
  "displacement-adds-readings": {
    id: "displacement-adds-readings",
    label: "складывает два показания",
    helpSectionId: "irregular-body-volume",
    shortHint: "Объём тела равен увеличению показания, поэтому из второго отсчёта вычитают первый.",
  },
  "displacement-takes-initial-reading": {
    id: "displacement-takes-initial-reading",
    label: "принимает начальный объём воды за объём тела",
    helpSectionId: "irregular-body-volume",
    shortHint: "Первое показание относится только к воде до погружения тела.",
  },
  "wrong-force-direction": {
    id: "wrong-force-direction",
    label: "складывает силы без направлений",
    helpSectionId: "resultant-force",
    shortHint: "Силы складываются как векторы: сначала ось и знаки, потом сумма.",
  },
  "friction-normal-force": {
    id: "friction-normal-force",
    label: "берет неверную реакцию опоры",
    helpSectionId: "friction",
    shortHint: "Трение равно μN; сначала найди N для конкретной опоры.",
  },
  "incline-projection-swap": {
    id: "incline-projection-swap",
    label: "путает sin и cos на наклонной",
    helpSectionId: "incline",
    shortHint: "Вдоль плоскости работает mg·sin α, поперёк — mg·cos α.",
  },
  "lift-acceleration-sign": {
    id: "lift-acceleration-sign",
    label: "выбирает знак по скорости лифта",
    helpSectionId: "weight-lift",
    shortHint: "Вес P и реакция N равны по модулю, но приложены к разным телам; знак задаёт ускорение.",
  },
  "impulse-resultant-force": {
    id: "impulse-resultant-force",
    label: "берёт импульс одной силы вместо равнодействующей",
    helpSectionId: "impulse-force",
    shortHint: "Изменение импульса задаёт импульс равнодействующей всех сил.",
  },
  "momentum-not-conserved": {
    id: "momentum-not-conserved",
    label: "не сохраняет импульс системы",
    helpSectionId: "momentum",
    shortHint: "Для сцепившихся тел сохраняется суммарный импульс до и после.",
  },
  "work-sign-error": {
    id: "work-sign-error",
    label: "не учитывает знак работы",
    helpSectionId: "work-energy",
    shortHint: "Работа отрицательна, если сила направлена против перемещения.",
  },
  "ohm-transform-error": {
    id: "ohm-transform-error",
    label: "ошибка в преобразовании закона Ома",
    helpSectionId: "ohms-law",
    shortHint: "Сначала вырази нужную величину из I = U/R, потом подставляй числа.",
  },
  "torque-arm-confusion": {
    id: "torque-arm-confusion",
    label: "путает плечо с расстоянием до точки приложения",
    helpSectionId: "torque-balance",
    shortHint: "Плечо силы — перпендикуляр от оси до линии действия силы.",
  },
  "wire-area-inverted": {
    id: "wire-area-inverted",
    label: "умножает сопротивление на площадь сечения",
    helpSectionId: "conductor-resistance",
    shortHint: "В $R=\\rho l/S$ площадь поперечного сечения стоит в знаменателе.",
  },
  "internal-resistance-missed": {
    id: "internal-resistance-missed",
    label: "теряет внутреннее сопротивление",
    helpSectionId: "full-circuit",
    shortHint: "В полной цепи ток ограничивает сумма внешнего и внутреннего сопротивлений.",
  },
  "source-efficiency-counts-loss": {
    id: "source-efficiency-counts-loss",
    label: "считает внутренние потери полезной мощностью",
    helpSectionId: "full-circuit",
    shortHint: "Полезная мощность поступает на R; сравни её с мощностью источника, развиваемой на R и r.",
  },
  "charge-not-conserved": {
    id: "charge-not-conserved",
    label: "не сохраняет общий заряд",
    helpSectionId: "charge-sharing",
    shortHint: "Перед делением сложи заряды с учетом знаков.",
  },
  "capacitor-square-law": {
    id: "capacitor-square-law",
    label: "теряет квадрат напряжения",
    helpSectionId: "capacitor-energy",
    shortHint: "Энергия конденсатора пропорциональна U² и содержит множитель 1/2.",
  },
  "lc-period-microfarads": {
    id: "lc-period-microfarads",
    label: "подставляет микрофарады без перевода в фарады",
    helpSectionId: "lc-period",
    shortHint: "Перед применением $T=2\\pi\\sqrt{LC}$ переведи мкФ в Ф: $1\\,\\text{мкФ}=10^{-6}\\,\\text{Ф}$.",
  },
  "ac-oscillogram-milliseconds": {
    id: "ac-oscillogram-milliseconds",
    label: "считает миллисекунды секундами",
    helpSectionId: "ac-oscillogram-frequency",
    shortHint: "Соседние максимумы одного знака дают полный период; переведи разность времён из мс в с перед расчётом частоты.",
  },
  "transformer-inverts-turns": {
    id: "transformer-inverts-turns",
    label: "переворачивает отношение числа витков",
    helpSectionId: "transformer-voltage-ratio",
    shortHint: "Для напряжения вторичной обмотки умножай U₁ на N₂/N₁, а не на N₁/N₂.",
  },
  "line-loss-missing-square": {
    id: "line-loss-missing-square",
    label: "забывает квадрат тока при расчёте нагрева",
    helpSectionId: "transmission-line-loss",
    shortHint: "Сначала вычисли ток P/U; мощность нагрева того же провода равна I²R.",
  },
  "em-wavelength-forgets-mega": {
    id: "em-wavelength-forgets-mega",
    label: "считает мегагерцы герцами",
    helpSectionId: "em-wavelength-vacuum",
    shortHint: "1 МГц — это миллион герц. Переведи частоту перед делением скорости на неё.",
  },
  "induction-missing-turns": {
    id: "induction-missing-turns",
    label: "забывает число витков",
    helpSectionId: "induced-emf-magnitude",
    shortHint: "Для одинаково ориентированных витков модуль ЭДС всей катушки в N раз больше, чем одного витка.",
  },
  "ampere-ignores-angle": {
    id: "ampere-ignores-angle",
    label: "не учитывает угол между током и полем",
    helpSectionId: "ampere-force-magnitude",
    shortHint: "При 30° сила вдвое меньше максимума при тех же B, I и длине: sin 30° = 0,5.",
  },
  "lorentz-millitesla-unit": {
    id: "lorentz-millitesla-unit",
    label: "считает миллитеслы теслами",
    helpSectionId: "lorentz-force-magnitude",
    shortHint: "Перед расчётом силы раздели значение индукции в мТл на 1000.",
  },
  "metal-source-condition": {
    id: "metal-source-condition",
    label: "не удерживает условие об источнике",
    helpSectionId: "metal-temperature-current",
    shortHint: "При постоянном напряжении I = U/R, а при постоянном токе источник должен изменить U вместе с R.",
  },
  "electrolyte-carrier-polarity": {
    id: "electrolyte-carrier-polarity",
    label: "путает носители заряда и полярность электродов",
    helpSectionId: "electrolyte-ion-transport",
    shortHint: "В растворе соли заряд переносят ионы; положительные движутся к отрицательному катоду, отрицательные — к аноду.",
  },
  "gas-ionizer-condition": {
    id: "gas-ionizer-condition",
    label: "не различает внешний и самостоятельный газовый разряд",
    helpSectionId: "gas-discharge-conditions",
    shortHint: "Смотри, продолжится ли разряд после удаления внешнего ионизатора при заданных условиях поля.",
  },
  "semiconductor-carrier-model": {
    id: "semiconductor-carrier-model",
    label: "смешивает дырки, ионы и суммарный заряд кристалла",
    helpSectionId: "semiconductor-carriers",
    shortHint: "Дырка — модель пустого места в связи. Тип n или p показывает основных носителей, но кристалл остаётся нейтральным.",
  },
  "self-induction-missing-time": {
    id: "self-induction-missing-time",
    label: "не учитывает время изменения тока",
    helpSectionId: "self-induction-emf",
    shortHint: "При неизменных L и ΔI модуль средней ЭДС обратно пропорционален времени изменения.",
  },
  "electric-power-voltage-only": {
    id: "electric-power-voltage-only",
    label: "находит напряжение вместо мощности",
    helpSectionId: "electric-power",
    shortHint: "После U=IR нужно еще найти P=UI или P=I²R.",
  },
  "temperature-celsius-kelvin": {
    id: "temperature-celsius-kelvin",
    label: "подставляет температуру в градусах Цельсия",
    helpSectionId: "gas-equation",
    shortHint: "В pV = νRT температура всегда в кельвинах.",
  },
  "heat-delta-temperature": {
    id: "heat-delta-temperature",
    label: "берет конечную температуру вместо изменения",
    helpSectionId: "heat-amount",
    shortHint: "В Q = cmΔT нужна разность температур.",
  },
  "heat-balance-arithmetic-mean": {
    id: "heat-balance-arithmetic-mean",
    label: "усредняет температуры без учета масс",
    helpSectionId: "heat-balance",
    shortHint: "В тепловом балансе массы задают вклад горячей и холодной воды.",
  },
  "elementary-charge-scale": {
    id: "elementary-charge-scale",
    label: "теряет масштаб элементарного заряда",
    helpSectionId: "elementary-charge",
    shortHint: "Одинаковый множитель 10⁻¹⁹ сокращается; раздели коэффициент заряда на 1,6.",
  },
  "fuel-specific-heat-missed": {
    id: "fuel-specific-heat-missed",
    label: "не учитывает массу топлива",
    helpSectionId: "fuel-combustion",
    shortHint: "Значение q относится к одному килограмму топлива; для массы m используй Q=qm.",
  },
  "melting-plateau-misread": {
    id: "melting-plateau-misread",
    label: "смешивает нагрев и плавление",
    helpSectionId: "heating-melting",
    shortHint: "Нагрев и плавление считаются разными стадиями и складываются.",
  },
  "vaporization-stage-omission": {
    id: "vaporization-stage-omission",
    label: "пропускает нагревание или парообразование",
    helpSectionId: "vaporization",
    shortHint: "Если вода начинает ниже 100 °C, отдельно посчитай нагревание и парообразование.",
  },
  "shadow-source-size": {
    id: "shadow-source-size",
    label: "не учитывает размер источника света",
    helpSectionId: "shadow-and-penumbra",
    shortHint: "Точечный источник даёт резкую границу; у протяжённого источника появляется область частичного освещения — полутень.",
  },
  "angle-from-surface": {
    id: "angle-from-surface",
    label: "отсчитывает углы от поверхности",
    helpSectionId: "reflection",
    shortHint: "Углы падения, отражения и преломления отсчитываются от нормали.",
  },
  "mirror-image-distance": {
    id: "mirror-image-distance",
    label: "путает расстояние до зеркала и до изображения",
    helpSectionId: "plane-mirror",
    shortHint: "Изображение за зеркалом на том же расстоянии: между предметом и изображением 2d.",
  },
  "refraction-density-direction": {
    id: "refraction-density-direction",
    label: "путает поворот луча при смене среды",
    helpSectionId: "refraction-direction",
    shortHint: "Из воздуха в воду луч отклоняется к нормали; из воды в воздух — от нормали.",
  },
  "refractive-index-inverted": {
    id: "refractive-index-inverted",
    label: "переворачивает отношение скоростей",
    helpSectionId: "refractive-index",
    shortHint: "В этих задачах n = c/v для обычной прозрачной среды в видимом свете, поэтому n > 1.",
  },
  "snell-without-sines": {
    id: "snell-without-sines",
    label: "делит углы вместо синусов",
    helpSectionId: "refraction",
    shortHint: "Закон преломления связывает синусы углов, а не сами углы.",
  },
  "lens-equation-sign": {
    id: "lens-equation-sign",
    label: "ошибается в знаменателе формулы линзы",
    helpSectionId: "thin-lens",
    shortHint: "Для действительного изображения f = F·d/(d − F): в знаменателе разность.",
  },
  "diopter-unit-conversion": {
    id: "diopter-unit-conversion",
    label: "не переводит фокусное расстояние в метры",
    helpSectionId: "optical-power",
    shortHint: "Диоптрия — это 1/м: сначала переведи F в метры.",
  },
  "magnification-inverted": {
    id: "magnification-inverted",
    label: "переворачивает отношение расстояний",
    helpSectionId: "magnification",
    shortHint: "Увеличение равно f/d — расстояние до изображения в числителе.",
  },
  "lens-image-kind": {
    id: "lens-image-kind",
    label: "путает действительное и мнимое изображение",
    helpSectionId: "lens-image-properties",
    shortHint: "Экран ловит изображение только там, где пересекаются сами лучи; пересечение продолжений даёт мнимое изображение.",
  },
  "vision-correction-sign": {
    id: "vision-correction-sign",
    label: "путает знак корректирующей линзы",
    helpSectionId: "vision-correction",
    shortHint: "Если фокус перед сетчаткой, его сдвигают назад рассеивающей линзой; если за сетчаткой — вперёд собирающей.",
  },
  "bohr-energy-sum": {
    id: "bohr-energy-sum",
    label: "складывает модули энергий уровней",
    helpSectionId: "atomic-transitions",
    shortHint: "Энергия фотона — модуль разности начального и конечного уровней.",
  },
  "bohr-level-square": {
    id: "bohr-level-square",
    label: "не возводит номер уровня в квадрат",
    helpSectionId: "atomic-transitions",
    shortHint: "Для атома водорода энергия уровня пропорциональна $-1/n^2$.",
  },
  "bohr-single-level": {
    id: "bohr-single-level",
    label: "использует энергию одного уровня",
    helpSectionId: "atomic-transitions",
    shortHint: "Сначала вычисли обе энергии, затем найди их разность.",
  },
};

export const taskLearningMetadataByTemplateId: Record<string, TaskLearningMetadata> = {
  "oscillation-frequency": {
    templateId: "oscillation-frequency",
    topicId: "dynamics",
    helpSectionId: "oscillations",
    skillId: "oscillation-frequency",
    focusLabel: "Частота механических колебаний",
    shortHint: "Частота — число полных циклов за секунду: ν = N/Δt; период T = 1/ν.",
    misconceptionIds: ["oscillation-frequency-inverted"],
  },
  "spring-oscillation-period": {
    templateId: "spring-oscillation-period",
    topicId: "dynamics",
    helpSectionId: "oscillations",
    skillId: "spring-oscillation-period",
    focusLabel: "Период пружинного маятника",
    shortHint: "Используй $T=2\\pi\\sqrt{m/k}$ и проверь единицы массы, жёсткости и периода.",
    misconceptionIds: ["spring-period-missing-root", "spring-period-inverted-ratio"],
  },
  "mathematical-pendulum-period": {
    templateId: "mathematical-pendulum-period",
    topicId: "dynamics",
    helpSectionId: "oscillations",
    skillId: "mathematical-pendulum-period",
    focusLabel: "Период математического маятника",
    shortHint: "Для малых углов используй $T=2\\pi\\sqrt{l/g}$; длину отсчитывают до центра груза.",
    misconceptionIds: ["pendulum-period-missing-root", "pendulum-period-inverted-ratio"],
  },
  "oscillation-energy": {
    templateId: "oscillation-energy",
    topicId: "dynamics",
    helpSectionId: "oscillations",
    skillId: "oscillation-energy",
    focusLabel: "Энергия гармонических колебаний",
    shortHint: "Найди полную энергию при амплитуде, затем вычти энергию пружины при данном смещении.",
    misconceptionIds: ["oscillation-energy-confuses-forms"],
  },
  "mechanical-wave-speed": {
    templateId: "mechanical-wave-speed",
    topicId: "dynamics",
    helpSectionId: "oscillations",
    skillId: "mechanical-wave-speed",
    focusLabel: "Скорость механической волны",
    shortHint: "Найди скорость как произведение длины волны и частоты: v = λν.",
    misconceptionIds: ["mechanical-wave-speed-divides", "mechanical-wave-speed-inverts", "mechanical-wave-speed-adds"],
  },
  "echo-ranging": {
    templateId: "echo-ranging",
    topicId: "dynamics",
    helpSectionId: "oscillations",
    skillId: "echo-ranging",
    focusLabel: "Глубина по эхосигналу",
    shortHint: "Найди полный путь импульса как vΔt, затем раздели его на два: сигнал вернулся после отражения.",
    misconceptionIds: ["echo-ranging-misses-return", "echo-ranging-halves-twice", "echo-ranging-inverts-time"],
  },
  "resonance-frequency-match": {
    templateId: "resonance-frequency-match",
    topicId: "dynamics",
    helpSectionId: "oscillations",
    skillId: "resonance-frequency-match",
    focusLabel: "Условие резонанса",
    shortHint: "Сравни частоту внешних толчков с собственной частотой системы: при близких значениях отклик сильнее.",
    misconceptionIds: ["resonance-frequency-match-half", "resonance-frequency-match-double", "resonance-frequency-match-period"],
  },
  "archimedes-force": {
    templateId: "archimedes-force",
    topicId: "dynamics",
    helpSectionId: "archimedes-force",
    skillId: "archimedes-force",
    focusLabel: "Сила Архимеда",
    shortHint: "Переведи погружённый объём в м³, затем умножь плотность среды, g и этот объём.",
  },
  "ship-payload": {
    templateId: "ship-payload",
    topicId: "dynamics",
    helpSectionId: "ship-payload",
    skillId: "ship-payload",
    focusLabel: "Грузоподъёмность судна",
    shortHint: "Вычти массу судна без груза из водоизмещения при предельной осадке.",
  },
  "contact-pressure":{templateId:"contact-pressure",topicId:"dynamics",helpSectionId:"contact-pressure",skillId:"contact-pressure",focusLabel:"Давление на опору",shortHint:"Вырази искомую величину из p=F/S: F — полная сила, S — общая площадь контакта. Согласуй Па, Н и м²."},
  "free-fall": {
    templateId: "free-fall",
    topicId: "kinematics",
    helpSectionId: "accelerated-motion",
    skillId: "free-fall",
    focusLabel: "Свободное падение",
    shortHint: "Свободное падение из покоя — равноускоренное движение с ускорением g.",
    misconceptionIds: ["forgot-acceleration-term"],
  },
  "vt-slope": {
    templateId: "vt-slope",
    topicId: "kinematics",
    helpSectionId: "motion-graphs",
    skillId: "vt-slope",
    focusLabel: "Наклон графика v(t)",
    shortHint: "Наклон v(t) показывает ускорение на выбранном участке.",
    misconceptionIds: ["slope-vs-area"],
  },
  "vt-area": {
    templateId: "vt-area",
    topicId: "kinematics",
    helpSectionId: "motion-graphs",
    skillId: "vt-area",
    focusLabel: "Площадь под графиком v(t)",
    shortHint: "Площадь под v(t) показывает перемещение за весь интервал.",
    misconceptionIds: ["vt-area-not-final-speed", "slope-vs-area"],
  },
  "relative-velocity-vectors": {
    templateId: "relative-velocity-vectors",
    topicId: "kinematics",
    helpSectionId: "vectors-relative-motion",
    skillId: "relative-velocity-vectors",
    focusLabel: "Относительная скорость",
    shortHint: "Найди скорость тела относительно другого тела. Учитывай не только значения скоростей, но и их направления.",
  },
  "average-speed-segments": {
    templateId: "average-speed-segments",
    topicId: "kinematics",
    helpSectionId: "average-speed",
    skillId: "average-speed-segments",
    focusLabel: "Средняя путевая скорость",
    shortHint: "Считай среднюю путевую скорость через весь путь и всё время движения.",
    misconceptionIds: ["average-speed-arithmetic-mean"],
  },
  "projectile-components": {
    templateId: "projectile-components",
    topicId: "kinematics",
    helpSectionId: "accelerated-motion",
    skillId: "projectile-components",
    focusLabel: "Бросок под углом по компонентам",
    shortHint: "Раздели скорость на v₀ₓ и v₀ᵧ: вертикаль задаёт время, горизонталь — дальность за это время.",
    misconceptionIds: ["projectile-axis-components"],
  },
  "rotation-frequency": {
    templateId: "rotation-frequency",
    topicId: "kinematics",
    helpSectionId: "circular-motion",
    skillId: "rotation-frequency",
    focusLabel: "Частота вращения",
    shortHint: "Частота показывает число полных оборотов за одну секунду.",
  },
  "centripetal-acceleration": {
    templateId: "centripetal-acceleration",
    topicId: "kinematics",
    helpSectionId: "circular-motion",
    skillId: "centripetal-acceleration",
    focusLabel: "Центростремительное ускорение",
    shortHint: "Ускорение направлено к центру, а модуль равен a = v²/R.",
  },
  "average-speed-with-stop": {
    templateId: "average-speed-with-stop",
    topicId: "kinematics",
    helpSectionId: "average-speed",
    skillId: "average-speed-with-stop",
    focusLabel: "Средняя скорость с остановкой",
    shortHint: "Сложи весь путь и всё время, включая остановку.",
    misconceptionIds: ["average-speed-omits-stop", "average-speed-arithmetic-mean"],
  },
  "uniform-motion-basic": {
    templateId: "uniform-motion-basic",
    topicId: "kinematics",
    helpSectionId: "uniform-motion",
    skillId: "uniform-motion-basic",
    focusLabel: "Путь, скорость и время",
    shortHint: "Назови неизвестную величину и вырази её из связи s = vt.",
  },
  "uniform-coordinate-law": {
    templateId: "uniform-coordinate-law",
    topicId: "kinematics",
    helpSectionId: "uniform-motion-graphs",
    skillId: "uniform-coordinate-law",
    focusLabel: "Координата и знак скорости",
    shortHint: "Выбери направление оси и сохрани знак vₓ в формуле x = x₀ + vₓt.",
    misconceptionIds: ["uniform-motion-coordinate-sign"],
  },
  "uniform-motion-graphs": {
    templateId: "uniform-motion-graphs",
    topicId: "kinematics",
    helpSectionId: "uniform-motion-graphs",
    skillId: "uniform-motion-graphs",
    focusLabel: "Графики s(t) и v(t)",
    shortHint: "Прочитай подписи осей, затем определи, что показывает наклон или высота линии.",
    misconceptionIds: ["uniform-motion-graph-reading"],
  },
  "unit-conversion-speed": {
    templateId: "unit-conversion-speed",
    topicId: "kinematics",
    helpSectionId: "units-conversion",
    skillId: "unit-conversion-speed",
    focusLabel: "Перевод скорости",
    shortHint: "Перед расчетом пути переведи км/ч в м/с, а минуты в секунды.",
    misconceptionIds: ["speed-unit-conversion"],
  },
  "length-unit-conversion": {
    templateId: "length-unit-conversion",
    topicId: "measurements",
    helpSectionId: "units-conversion",
    skillId: "length-unit-conversion",
    focusLabel: "Перевод длины в метры",
    shortHint: "Сверь множитель: 1 км = 1000 м, 1 дм = 0,1 м, 1 см = 0,01 м, 1 мм = 0,001 м.",
    misconceptionIds: ["length-unit-conversion-direction"],
  },
  "graduated-scale-reading": {
    templateId: "graduated-scale-reading",
    topicId: "measurements",
    helpSectionId: "graduated-scale",
    skillId: "graduated-scale-reading",
    focusLabel: "Показание мензурки",
    shortHint: "Из общего числа штрихов с крайними отметками отними один; так получишь число промежутков для цены деления.",
    misconceptionIds: [
      "graduated-scale-omits-base",
      "graduated-scale-counts-marks",
      "graduated-scale-one-step-extra",
    ],
  },
  "rectangular-block-volume": {
    templateId: "rectangular-block-volume",
    topicId: "measurements",
    helpSectionId: "rectangular-block-volume",
    skillId: "rectangular-block-volume",
    focusLabel: "Объём бруска по измеренным рёбрам",
    shortHint: "Сначала вырази рёбра в сантиметрах, затем вычисли $V=abc$ и запиши см³.",
    misconceptionIds: ["block-volume-omits-third-edge", "block-volume-adds-height", "block-volume-adds-edges"],
  },
  "irregular-body-volume": {
    templateId: "irregular-body-volume",
    topicId: "measurements",
    helpSectionId: "irregular-body-volume",
    skillId: "irregular-body-volume",
    focusLabel: "Объём тела по двум отсчётам",
    shortHint: "Полностью погрузи тело без потери воды и вычти первое показание мензурки из второго.",
    misconceptionIds: ["displacement-takes-final-reading", "displacement-adds-readings", "displacement-takes-initial-reading"],
  },
  "gravity-force": {
    templateId: "gravity-force",
    topicId: "dynamics",
    helpSectionId: "gravity-force",
    skillId: "gravity-force",
    focusLabel: "Сила тяжести и масса",
    shortHint: "Сила тяжести равна массе, умноженной на g; ответ записывают в ньютонах.",
  },
  "gravitation-distance": {
    templateId: "gravitation-distance",
    topicId: "dynamics",
    helpSectionId: "gravitation-distance",
    skillId: "gravitation-distance",
    focusLabel: "Квадрат расстояния в законе тяготения",
    shortHint: "Возведи коэффициент изменения расстояния в квадрат; сила изменится во столько раз в противоположную сторону.",
  },
  "hydrostatic-pressure": {templateId:"hydrostatic-pressure",topicId:"dynamics",helpSectionId:"hydrostatic-pressure",skillId:"hydrostatic-pressure",focusLabel:"Давление жидкости на глубине",shortHint:"Умножь плотность на g и глубину, затем переведи паскали в килопаскали."},
  "newton-second": {
    templateId: "newton-second",
    topicId: "dynamics",
    helpSectionId: "newton-second-law",
    skillId: "newton-second",
    focusLabel: "Второй закон Ньютона",
    shortHint: "Сравни все силы и найди ту, что остаётся: она вместе с массой задаёт ускорение.",
    misconceptionIds: ["wrong-force-direction"],
  },
  "friction-force": {
    templateId: "friction-force",
    topicId: "dynamics",
    helpSectionId: "friction",
    skillId: "friction-force",
    focusLabel: "Сила трения",
    shortHint: "Трение равно μN; сначала найди реакцию опоры.",
    misconceptionIds: ["friction-normal-force"],
  },
  "incline-force": {
    templateId: "incline-force",
    topicId: "dynamics",
    helpSectionId: "incline",
    skillId: "incline-force",
    focusLabel: "Наклонная плоскость",
    shortHint: "Разложи mg вдоль плоскости и перпендикулярно ей.",
    misconceptionIds: ["incline-projection-swap", "friction-normal-force"],
  },
  "resultant-force": {
    templateId: "resultant-force",
    topicId: "dynamics",
    helpSectionId: "resultant-force",
    skillId: "resultant-force",
    focusLabel: "Равнодействующая сил",
    shortHint: "Сначала отметь направления: силы навстречу гасят друг друга, силы в одну сторону складываются.",
    misconceptionIds: ["wrong-force-direction"],
  },
  "resultant-force-2d": {
    templateId: "resultant-force-2d",
    topicId: "dynamics",
    helpSectionId: "resultant-force",
    skillId: "resultant-force-2d",
    focusLabel: "Равнодействующая перпендикулярных сил",
    shortHint: "Перпендикулярные силы складываются по теореме Пифагора.",
    misconceptionIds: ["wrong-force-direction"],
  },
  "weight-lift": {
    templateId: "weight-lift",
    topicId: "dynamics",
    helpSectionId: "weight-lift",
    skillId: "weight-lift",
    focusLabel: "Вес тела в лифте",
    shortHint: "Вес P и реакция N равны по модулю при контакте; знак зависит от ускорения опоры.",
    misconceptionIds: ["lift-acceleration-sign"],
  },
  "inelastic-collision-speed": {
    templateId: "inelastic-collision-speed",
    topicId: "dynamics",
    helpSectionId: "momentum",
    skillId: "inelastic-collision-speed",
    focusLabel: "Неупругое столкновение",
    shortHint: "После сцепления тел общий импульс делится на общую массу.",
    misconceptionIds: ["momentum-not-conserved"],
  },
  "kinetic-energy": {
    templateId: "kinetic-energy",
    topicId: "dynamics",
    helpSectionId: "kinetic-energy",
    skillId: "kinetic-energy",
    focusLabel: "Кинетическая энергия",
    shortHint: "Кинетическая энергия зависит от квадрата скорости.",
  },
  "torque-balance": {
    templateId: "torque-balance",
    topicId: "dynamics",
    helpSectionId: "torque-balance",
    skillId: "torque-balance",
    focusLabel: "Равновесие моментов сил",
    shortHint: "Сравни произведения каждой силы на её перпендикулярное плечо.",
    misconceptionIds: ["torque-arm-confusion"],
  },
  "movable-pulley": {
    templateId: "movable-pulley",
    topicId: "dynamics",
    helpSectionId: "movable-pulley",
    skillId: "movable-pulley",
    focusLabel: "Выигрыш в силе подвижного блока",
    shortHint: "Две несущие ветви делят вес груза поровну.",
  },
  "gravitational-potential-energy": {
    templateId: "gravitational-potential-energy",
    topicId: "dynamics",
    helpSectionId: "potential-energy",
    skillId: "gravitational-potential-energy",
    focusLabel: "Потенциальная энергия",
    shortHint: "Высоту отсчитывай от указанного нулевого уровня: Eₚ = mgh.",
  },
  "mechanical-energy-conservation": {
    templateId: "mechanical-energy-conservation",
    topicId: "dynamics",
    helpSectionId: "energy-conservation",
    skillId: "mechanical-energy-conservation",
    focusLabel: "Сохранение механической энергии",
    shortHint: "Без сопротивления сумма Eₖ + Eₚ остаётся постоянной.",
  },
  "density-volume-ratio": {
    templateId: "density-volume-ratio",
    topicId: "thermodynamics",
    helpSectionId: "density-volume",
    skillId: "density-volume-ratio",
    focusLabel: "Плотность и объём",
    shortHint: "Масса пропорциональна плотности и объёму, а не линейному размеру.",
  },
  "impulse-momentum": {
    templateId: "impulse-momentum",
    topicId: "dynamics",
    helpSectionId: "impulse-force",
    skillId: "impulse-momentum",
    focusLabel: "Импульс силы",
    shortHint: "Импульс равнодействующей всех сил равен изменению импульса тела.",
    misconceptionIds: ["impulse-resultant-force"],
  },
  "work-force-distance": {
    templateId: "work-force-distance",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "work-force-distance",
    focusLabel: "Работа силы",
    shortHint: "Смотри на направление силы относительно перемещения: знак работы меняется.",
    misconceptionIds: ["work-sign-error"],
  },
  "work-at-angle": {
    templateId: "work-at-angle",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "work-at-angle",
    focusLabel: "Работа силы под углом",
    shortHint: "Найди проекцию силы на направление перемещения и учти знак косинуса.",
  },
  "mechanical-power": {
    templateId: "mechanical-power",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "mechanical-power",
    focusLabel: "Механическая мощность",
    shortHint: "Мощность показывает работу за единицу времени: P = A/t.",
  },
  "mechanical-efficiency": {
    templateId: "mechanical-efficiency",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "mechanical-efficiency",
    focusLabel: "КПД механизма",
    shortHint: "КПД — доля полезной работы во всей совершённой работе.",
  },
  "ohm-law": {
    templateId: "ohm-law",
    topicId: "electrodynamics",
    helpSectionId: "ohms-law",
    skillId: "ohm-law",
    focusLabel: "Закон Ома",
    shortHint: "Свяжи ток, напряжение и сопротивление до подстановки чисел.",
    misconceptionIds: ["ohm-transform-error"],
  },
  "conductor-resistance": {
    templateId: "conductor-resistance",
    topicId: "electrodynamics",
    helpSectionId: "conductor-resistance",
    skillId: "conductor-resistance",
    focusLabel: "Сопротивление проводника",
    shortHint: "Согласуй единицы ρ, l и S, затем используй $R=\\rho l/S$.",
    misconceptionIds: ["wire-area-inverted"],
  },
  "resistor-network": {
    templateId: "resistor-network",
    topicId: "electrodynamics",
    helpSectionId: "ohms-law",
    skillId: "resistor-network",
    focusLabel: "Соединения резисторов",
    shortHint: "Сначала найди эквивалентное сопротивление, затем применяй закон Ома.",
    misconceptionIds: ["ohm-transform-error"],
  },
  "source-internal-resistance": {
    templateId: "source-internal-resistance",
    topicId: "electrodynamics",
    helpSectionId: "full-circuit",
    skillId: "source-internal-resistance",
    focusLabel: "Полная цепь",
    shortHint: "Во всей цепи учитывай внешнее и внутреннее сопротивление.",
    misconceptionIds: ["internal-resistance-missed"],
  },
  "source-efficiency": {
    templateId: "source-efficiency",
    topicId: "electrodynamics",
    helpSectionId: "full-circuit",
    skillId: "source-efficiency",
    focusLabel: "КПД источника",
    shortHint: "КПД — полезная мощность на нагрузке, делённая на мощность источника.",
    misconceptionIds: ["source-efficiency-counts-loss"],
  },
  "capacitor-energy": {
    templateId: "capacitor-energy",
    topicId: "electrodynamics",
    helpSectionId: "capacitor-energy",
    skillId: "capacitor-energy",
    focusLabel: "Энергия конденсатора",
    shortHint: "Энергия конденсатора зависит от U² и множителя 1/2.",
    misconceptionIds: ["capacitor-square-law"],
  },
  "lc-period": {
    templateId: "lc-period",
    topicId: "electrodynamics",
    helpSectionId: "lc-period",
    skillId: "lc-period",
    focusLabel: "Период свободных колебаний в LC-контуре",
    shortHint: "Переведи C из мкФ в Ф, вычисли $T=2\\pi\\sqrt{LC}$ в секундах и переведи в мс.",
    misconceptionIds: ["lc-period-microfarads"],
  },
  "ac-oscillogram-frequency": {
    templateId: "ac-oscillogram-frequency",
    topicId: "electrodynamics",
    helpSectionId: "ac-oscillogram-frequency",
    skillId: "ac-oscillogram-frequency",
    focusLabel: "Частота переменного тока по двум максимумам",
    shortHint: "Найди полный период между соседними положительными максимумами и переведи мс в с.",
    misconceptionIds: ["ac-oscillogram-milliseconds"],
  },
  "transformer-voltage-ratio": {
    templateId: "transformer-voltage-ratio",
    topicId: "electrodynamics",
    helpSectionId: "transformer-voltage-ratio",
    skillId: "transformer-voltage-ratio",
    focusLabel: "Напряжение вторичной обмотки",
    shortHint: "Сравни витки первичной и вторичной обмоток, затем найди U₂ по отношению N₂/N₁.",
    misconceptionIds: ["transformer-inverts-turns"],
  },
  "transmission-line-loss": {
    templateId: "transmission-line-loss",
    topicId: "electrodynamics",
    helpSectionId: "transmission-line-loss",
    skillId: "transmission-line-loss",
    focusLabel: "Мощность нагрева линии",
    shortHint: "При прежней мощности на входе найди ток P/U, затем возведи его в квадрат и умножь на сопротивление линии.",
    misconceptionIds: ["line-loss-missing-square"],
  },
  "em-wavelength-vacuum": {
    templateId: "em-wavelength-vacuum",
    topicId: "electrodynamics",
    helpSectionId: "em-wavelength-vacuum",
    skillId: "em-wavelength-vacuum",
    focusLabel: "Длина радиоволны в вакууме",
    shortHint: "Переведи частоту из МГц в Гц и найди длину волны по λ = c/ν.",
    misconceptionIds: ["em-wavelength-forgets-mega"],
  },
  "induced-emf-magnitude": {
    templateId: "induced-emf-magnitude",
    topicId: "electrodynamics",
    helpSectionId: "induced-emf-magnitude",
    skillId: "induced-emf-magnitude",
    focusLabel: "Модуль ЭДС по изменению магнитного потока",
    shortHint: "Умножь изменение потока одного витка на число витков и раздели на время; согласуй мВб и мс.",
    misconceptionIds: ["induction-missing-turns"],
  },
  "ampere-force-magnitude": {
    templateId: "ampere-force-magnitude",
    topicId: "electrodynamics",
    helpSectionId: "ampere-force-magnitude",
    skillId: "ampere-force-magnitude",
    focusLabel: "Модуль силы Ампера",
    shortHint: "Прямой участок в однородном поле: F = BIℓ sin α; переведи мТл и см в единицы СИ.",
    misconceptionIds: ["ampere-ignores-angle"],
  },
  "lorentz-force-magnitude": {
    templateId: "lorentz-force-magnitude",
    topicId: "electrodynamics",
    helpSectionId: "lorentz-force-magnitude",
    skillId: "lorentz-force-magnitude",
    focusLabel: "Модуль магнитной силы Лоренца",
    shortHint: "При v поперёк B умножь |q|vB; переведи мТл в Тл.",
    misconceptionIds: ["lorentz-millitesla-unit"],
  },
  "metal-temperature-current": {
    templateId: "metal-temperature-current",
    topicId: "electrodynamics",
    helpSectionId: "metal-temperature-current",
    skillId: "metal-temperature-current",
    focusLabel: "Ток в металле при нагреве",
    shortHint: "Сначала проверь, что источник удерживает: U или I. При постоянном U увеличение R уменьшает I.",
    misconceptionIds: ["metal-source-condition"],
  },
  "electrolyte-ion-transport": {
    templateId: "electrolyte-ion-transport",
    topicId: "electrodynamics",
    helpSectionId: "electrolyte-ion-transport",
    skillId: "electrolyte-ion-transport",
    focusLabel: "Носители заряда в растворе соли",
    shortHint: "Растворение не всегда даёт ионы. В растворе соли проверь знак иона и полярность электрода.",
    misconceptionIds: ["electrolyte-carrier-polarity"],
  },
  "gas-discharge-conditions": {
    templateId: "gas-discharge-conditions",
    topicId: "electrodynamics",
    helpSectionId: "gas-discharge-conditions",
    skillId: "gas-discharge-conditions",
    focusLabel: "Условия и носители тока в газе",
    shortHint: "В обычном воздухе мало свободных зарядов. Различи внешнюю ионизацию и разряд, сохраняющийся после её удаления.",
    misconceptionIds: ["gas-ionizer-condition"],
  },
  "semiconductor-carriers": {
    templateId: "semiconductor-carriers",
    topicId: "electrodynamics",
    helpSectionId: "semiconductor-carriers",
    skillId: "semiconductor-carriers",
    focusLabel: "Свет, нагрев и носители в полупроводнике",
    shortHint: "При прежнем U сравни R и I; в чистом образце различи электроны и дырки, в примесном — основных носителей.",
    misconceptionIds: ["semiconductor-carrier-model"],
  },
  "self-induction-emf": {
    templateId: "self-induction-emf",
    topicId: "electrodynamics",
    helpSectionId: "self-induction-emf",
    skillId: "self-induction-emf",
    focusLabel: "Модуль ЭДС самоиндукции",
    shortHint: "Возьми L·|ΔI|/Δt; перевод мГн и мс сокращается только при согласованных единицах.",
    misconceptionIds: ["self-induction-missing-time"],
  },
  "electric-power": {
    templateId: "electric-power",
    topicId: "electrodynamics",
    helpSectionId: "electric-power",
    skillId: "electric-power",
    focusLabel: "Мощность тока",
    shortHint: "Не останавливайся на U=IR: для мощности используй P=UI или P=I²R.",
    misconceptionIds: ["electric-power-voltage-only", "ohm-transform-error"],
  },
  "household-load-current": {
    templateId: "household-load-current",
    topicId: "electrodynamics",
    helpSectionId: "household-load-current",
    skillId: "household-load-current",
    focusLabel: "Общий ток двух приборов",
    shortHint: "Сложи мощности, затем раздели сумму на 220 В. Разбор сравнит ток с условным пределом 10 А.",
  },
  "charge-sharing": {
    templateId: "charge-sharing",
    topicId: "electrodynamics",
    helpSectionId: "charge-sharing",
    skillId: "charge-sharing",
    focusLabel: "Деление заряда",
    shortHint: "После контакта одинаковых проводников общий заряд делится поровну.",
    misconceptionIds: ["charge-not-conserved"],
  },
  "coulomb-force": {
    templateId: "coulomb-force",
    topicId: "electrodynamics",
    helpSectionId: "coulomb-force",
    skillId: "coulomb-force",
    focusLabel: "Сила между зарядами",
    shortHint: "Для модуля силы используй модули зарядов и квадрат расстояния.",
    misconceptionIds: [],
  },
  "electric-field-strength": {
    templateId: "electric-field-strength",
    topicId: "electrodynamics",
    helpSectionId: "electric-field-strength",
    skillId: "electric-field-strength",
    focusLabel: "Напряжённость поля",
    shortHint: "Для точечного источника E зависит от его заряда и расстояния до точки.",
    misconceptionIds: [],
  },
  "electric-field-superposition": {
    templateId: "electric-field-superposition",
    topicId: "electrodynamics",
    helpSectionId: "electric-field-superposition",
    skillId: "electric-field-superposition",
    focusLabel: "Сложение полей",
    shortHint: "Определи направление E от каждого источника в точке P, а затем сложи проекции со знаками.",
    misconceptionIds: [],
  },
  "electrostatic-field-work": {
    templateId: "electrostatic-field-work",
    topicId: "electrodynamics",
    helpSectionId: "electrostatic-field-work",
    skillId: "electrostatic-field-work",
    focusLabel: "Работа поля и энергия заряда",
    shortHint: "Учитывай знак заряда и проекцию смещения; изменение потенциальной энергии равно −A.",
    misconceptionIds: [],
  },
  "point-charge-potential": {
    templateId: "point-charge-potential",
    topicId: "electrodynamics",
    helpSectionId: "point-charge-potential",
    skillId: "point-charge-potential",
    focusLabel: "Потенциал точечного заряда",
    shortHint: "Знак задаёт заряд источника; потенциал в вакууме убывает как 1/r.",
    misconceptionIds: [],
  },
  "multi-source-potential": {
    templateId: "multi-source-potential",
    topicId: "electrodynamics",
    helpSectionId: "multi-source-potential",
    skillId: "multi-source-potential",
    focusLabel: "Потенциалы нескольких зарядов",
    shortHint: "Найди потенциал каждого источника в точке P и сложи значения со знаками их зарядов.",
    misconceptionIds: [],
  },
  "uniform-field-voltage": {
    templateId: "uniform-field-voltage",
    topicId: "electrodynamics",
    helpSectionId: "uniform-field-voltage",
    skillId: "uniform-field-voltage",
    focusLabel: "Напряжение в однородном поле",
    shortHint: "Учитывай порядок A→B и проекцию расстояния вдоль E.",
    misconceptionIds: [],
  },
  "parallel-plate-capacitance": {
    templateId: "parallel-plate-capacitance",
    topicId: "electrodynamics",
    helpSectionId: "parallel-plate-capacitance",
    skillId: "parallel-plate-capacitance",
    focusLabel: "Ёмкость плоского конденсатора",
    shortHint: "C растёт с площадью перекрытия и ε, но уменьшается с зазором d.",
    misconceptionIds: [],
  },
  "ideal-gas-state": {
    templateId: "ideal-gas-state",
    topicId: "thermodynamics",
    helpSectionId: "gas-equation",
    skillId: "ideal-gas-state",
    focusLabel: "Уравнение состояния газа",
    shortHint: "В pV = νRT температура всегда в кельвинах.",
    misconceptionIds: ["temperature-celsius-kelvin"],
  },
  "gas-state-ratio": {
    templateId: "gas-state-ratio",
    topicId: "thermodynamics",
    helpSectionId: "gas-equation",
    skillId: "gas-state-ratio",
    focusLabel: "Связь параметров газа",
    shortHint: "Для одной массы газа используй pV/T = const и температуру в кельвинах.",
    misconceptionIds: ["temperature-celsius-kelvin"],
  },
  "heat-amount": {
    templateId: "heat-amount",
    topicId: "thermodynamics",
    helpSectionId: "heat-amount",
    skillId: "heat-amount",
    focusLabel: "Количество теплоты",
    shortHint: "Q = cmΔT даёт теплоту тела при постоянной c, без фазового перехода; учитывай условие о потерях.",
    misconceptionIds: ["heat-delta-temperature"],
  },
  "heat-balance-simple": {
    templateId: "heat-balance-simple",
    topicId: "thermodynamics",
    helpSectionId: "heat-balance",
    skillId: "heat-balance-simple",
    focusLabel: "Тепловой баланс",
    shortHint: "При смешивании отданная горячей водой теплота равна полученной холодной.",
    misconceptionIds: ["heat-balance-arithmetic-mean"],
  },
  "ideal-gas-isoprocess": {
    templateId: "ideal-gas-isoprocess",
    topicId: "thermodynamics",
    helpSectionId: "gas-isoprocesses",
    skillId: "ideal-gas-isoprocess",
    focusLabel: "Законы изопроцессов",
    shortHint: "Определи, что постоянно: T, p или V; затем выбери обратную или прямую пропорциональность.",
    misconceptionIds: ["isoprocess-proportionality"],
  },
  "solid-structure-properties": {
    templateId: "solid-structure-properties",
    topicId: "thermodynamics",
    helpSectionId: "solid-structure",
    skillId: "solid-structure-properties",
    focusLabel: "Строение твёрдых тел",
    shortHint: "Определи, что задано: единая решётка, множество зёрен или аморфное состояние.",
    misconceptionIds: ["solid-structure-from-appearance"],
  },
  "liquid-structure-properties": {
    templateId: "liquid-structure-properties",
    topicId: "thermodynamics",
    helpSectionId: "liquid-structure",
    skillId: "liquid-structure-properties",
    focusLabel: "Строение жидкостей",
    shortHint: "Раздели движение частиц в объёме и нескомпенсированные силы поверхностного слоя.",
    misconceptionIds: ["liquid-bulk-surface-confusion"],
  },
  "vapor-dynamic-equilibrium": {
    templateId: "vapor-dynamic-equilibrium",
    topicId: "thermodynamics",
    helpSectionId: "vapor-equilibrium",
    skillId: "vapor-dynamic-equilibrium",
    focusLabel: "Испарение и насыщенный пар",
    shortHint: "Сравни два встречных потока молекул за одинаковое время и проверь, закрыта ли система.",
    misconceptionIds: ["vapor-equilibrium-means-stillness"],
  },
  "relative-humidity-pressure": {
    templateId: "relative-humidity-pressure",
    topicId: "thermodynamics",
    helpSectionId: "air-humidity",
    skillId: "relative-humidity-pressure",
    focusLabel: "Относительная влажность воздуха",
    shortHint: "Раздели фактическое давление пара на давление насыщенного пара при той же температуре и вырази долю в процентах.",
    misconceptionIds: ["relative-humidity-wrong-denominator"],
  },
  "monoatomic-internal-energy": {
    templateId: "monoatomic-internal-energy",
    topicId: "thermodynamics",
    helpSectionId: "internal-energy-gas",
    skillId: "monoatomic-internal-energy",
    focusLabel: "Внутренняя энергия одноатомного газа",
    shortHint: "Подставь количество вещества и абсолютную температуру в $U=\\frac32\\nu RT$, затем переведи джоули в килоджоули.",
    misconceptionIds: ["internal-energy-missing-factor"],
  },
  "isobaric-gas-work": {
    templateId: "isobaric-gas-work",
    topicId: "thermodynamics",
    helpSectionId: "gas-work",
    skillId: "isobaric-gas-work",
    focusLabel: "Работа газа при расширении",
    shortHint: "Найди ΔV и используй $A=p\\Delta V$. При кПа и литрах ответ получится в джоулях.",
    misconceptionIds: ["gas-work-uses-final-volume"],
  },
  "first-law-energy-balance": {
    templateId: "first-law-energy-balance",
    topicId: "thermodynamics",
    helpSectionId: "first-law",
    skillId: "first-law-energy-balance",
    focusLabel: "Первый закон термодинамики",
    shortHint: "Запиши знаки Q и A газа отдельно, затем найди $\\Delta U=Q-A_{\\text{газа}}$.",
    misconceptionIds: ["first-law-adds-gas-work"],
  },
  "heat-engine-efficiency": {
    templateId: "heat-engine-efficiency",
    topicId: "thermodynamics",
    helpSectionId: "heat-engine",
    skillId: "heat-engine-efficiency",
    focusLabel: "Термический КПД теплового двигателя",
    shortHint: "Найди работу за цикл $A_{\\text{ц}}=Q_1-|Q_2|$, затем её долю от $Q_1$ в процентах.",
    misconceptionIds: ["heat-engine-uses-cooler-heat"],
  },
  "molecule-count-from-mass": {
    templateId: "molecule-count-from-mass",
    topicId: "thermodynamics",
    helpSectionId: "amount-of-substance",
    skillId: "molecule-count-from-mass",
    focusLabel: "Число молекул",
    shortHint: "Сначала найди количество вещества ν = m/M, затем умножь его на постоянную Авогадро.",
    misconceptionIds: ["molecule-count-skips-molar-mass"],
  },
  "particle-concentration": {
    templateId: "particle-concentration",
    topicId: "thermodynamics",
    helpSectionId: "particle-concentration",
    skillId: "particle-concentration",
    focusLabel: "Концентрация частиц",
    shortHint: "Переведи объём в кубические метры и раздели число частиц на этот объём.",
    misconceptionIds: ["particle-concentration-volume-unit"],
  },
  "molecular-kinetic-energy": {
    templateId: "molecular-kinetic-energy",
    topicId: "thermodynamics",
    helpSectionId: "molecular-kinetic-energy",
    skillId: "molecular-kinetic-energy",
    focusLabel: "Средняя энергия молекул",
    shortHint: "Переведи температуру в кельвины и используй среднюю энергию 3kT/2.",
    misconceptionIds: ["molecular-energy-celsius"],
  },
  "elementary-charge-count": {
    templateId: "elementary-charge-count",
    topicId: "electrodynamics",
    helpSectionId: "elementary-charge",
    skillId: "elementary-charge-count",
    focusLabel: "Число элементарных зарядов",
    shortHint: "Сравни модуль заряда с e = 1,6 · 10⁻¹⁹ Кл.",
    misconceptionIds: ["elementary-charge-scale"],
  },
  "magnetic-field-direction": {
    templateId: "magnetic-field-direction",
    topicId: "electrodynamics",
    helpSectionId: "magnetic-field",
    skillId: "magnetic-field-direction",
    focusLabel: "Направление магнитного поля",
    shortHint: "Сначала установи направление тока, затем примени правило правой руки; северный конец стрелки показывает направление поля.",
  },
  "fuel-combustion-heat": {
    templateId: "fuel-combustion-heat",
    topicId: "thermodynamics",
    helpSectionId: "fuel-combustion",
    skillId: "fuel-combustion-heat",
    focusLabel: "Теплота сгорания топлива",
    shortHint: "При полном сгорании умножь удельную теплоту сгорания на массу топлива.",
    misconceptionIds: ["fuel-specific-heat-missed"],
  },
  "phase-change-heat": {
    templateId: "phase-change-heat",
    topicId: "thermodynamics",
    helpSectionId: "heating-melting",
    skillId: "phase-change-heat",
    focusLabel: "Нагревание и плавление",
    shortHint: "Нагрев и плавление считаются отдельными стадиями и складываются.",
    misconceptionIds: ["melting-plateau-misread", "heat-delta-temperature"],
  },
  "vaporization-heat": {
    templateId: "vaporization-heat",
    topicId: "thermodynamics",
    helpSectionId: "vaporization",
    skillId: "vaporization-heat",
    focusLabel: "Нагревание и парообразование",
    shortHint: "Сначала нагрей воду до температуры кипения, затем прибавь теплоту парообразования.",
    misconceptionIds: ["vaporization-stage-omission", "heat-delta-temperature"],
  },
  "reflection-angle": {
    templateId: "reflection-angle",
    topicId: "optics",
    helpSectionId: "reflection",
    skillId: "reflection-angle",
    focusLabel: "Закон отражения",
    shortHint: "Угол отражения равен углу падения; оба отсчитываются от нормали.",
    misconceptionIds: ["angle-from-surface"],
  },
  "plane-mirror-separation": {
    templateId: "plane-mirror-separation",
    topicId: "optics",
    helpSectionId: "plane-mirror",
    skillId: "plane-mirror-separation",
    focusLabel: "Плоское зеркало",
    shortHint: "Между предметом и мнимым изображением — удвоенное расстояние до зеркала.",
    misconceptionIds: ["mirror-image-distance"],
  },
  "shadow-and-penumbra": {
    templateId: "shadow-and-penumbra",
    topicId: "optics",
    helpSectionId: "shadow-and-penumbra",
    skillId: "shadow-and-penumbra",
    focusLabel: "Тень и полутень",
    shortHint: "Определи, точечный источник или протяжённый, затем проследи граничные лучи до экрана.",
    misconceptionIds: ["shadow-source-size"],
  },
  "refraction-direction": {
    templateId: "refraction-direction",
    topicId: "optics",
    helpSectionId: "refraction-direction",
    skillId: "refraction-direction",
    focusLabel: "Направление преломлённого луча",
    shortHint: "Отметь нормаль и направление перехода: в воду луч поворачивает к нормали, из воды в воздух — от нормали.",
    misconceptionIds: ["refraction-density-direction"],
  },
  "refractive-index-speed": {
    templateId: "refractive-index-speed",
    topicId: "optics",
    helpSectionId: "refractive-index",
    skillId: "refractive-index-speed",
    focusLabel: "Показатель преломления",
    shortHint: "n = c/v: c дели на фазовую скорость света в обычной прозрачной среде.",
    misconceptionIds: ["refractive-index-inverted"],
  },
  "snell-index-ratio": {
    templateId: "snell-index-ratio",
    topicId: "optics",
    helpSectionId: "refraction",
    skillId: "snell-index-ratio",
    focusLabel: "Закон преломления",
    shortHint: "Отношение показателей равно отношению синусов углов от нормали.",
    misconceptionIds: ["snell-without-sines", "angle-from-surface"],
  },
  "thin-lens-image-distance": {
    templateId: "thin-lens-image-distance",
    topicId: "optics",
    helpSectionId: "thin-lens",
    skillId: "thin-lens-image-distance",
    focusLabel: "Формула тонкой линзы",
    shortHint: "Вырази f из 1/F = 1/d + 1/f, следи за разностью в знаменателе.",
    misconceptionIds: ["lens-equation-sign"],
  },
  "lens-optical-power": {
    templateId: "lens-optical-power",
    topicId: "optics",
    helpSectionId: "optical-power",
    skillId: "lens-optical-power",
    focusLabel: "Оптическая сила",
    shortHint: "Переведи фокусное расстояние в метры и возьми обратную величину.",
    misconceptionIds: ["diopter-unit-conversion"],
  },
  "lens-image-height": {
    templateId: "lens-image-height",
    topicId: "optics",
    helpSectionId: "magnification",
    skillId: "lens-image-height",
    focusLabel: "Увеличение линзы",
    shortHint: "Модуль увеличения dᵢ/dₒ умножь на высоту предмета h.",
    misconceptionIds: ["magnification-inverted"],
  },
  "lens-image-properties": {
    templateId: "lens-image-properties",
    topicId: "optics",
    helpSectionId: "lens-image-properties",
    skillId: "lens-image-properties",
    focusLabel: "Свойства изображения в линзе",
    shortHint: "Расположи предмет относительно F и 2F, затем проверь, пересекаются лучи или их продолжения.",
    misconceptionIds: ["lens-image-kind"],
  },
  "vision-correction": {
    templateId: "vision-correction",
    topicId: "optics",
    helpSectionId: "vision-correction",
    skillId: "vision-correction",
    focusLabel: "Коррекция зрения линзами",
    shortHint: "Сначала найди фокус относительно сетчатки, затем выбери знак и тип линзы.",
    misconceptionIds: ["vision-correction-sign"],
  },
  "bohr-transition-radiation": {
    templateId: "bohr-transition-radiation",
    topicId: "quantum",
    helpSectionId: "atomic-transitions",
    skillId: "bohr-transition-radiation",
    focusLabel: "Энергия, частота и длина волны фотона",
    shortHint: "Найди энергии обоих уровней водорода; частота и длина волны связаны с модулем их разности.",
    misconceptionIds: ["bohr-energy-sum", "bohr-level-square", "bohr-single-level"],
  },
};

export function getTaskLearningMetadata(templateId: string | undefined) {
  if (!templateId) {
    return undefined;
  }

  return taskLearningMetadataByTemplateId[templateId];
}

export function getMisconceptionMetadata(misconceptionId: string | undefined) {
  if (!misconceptionId) {
    return undefined;
  }

  return misconceptionMetadataById[misconceptionId];
}

