import type { HelpSectionId } from "./topic-help.ts";
import type { TopicId } from "./taxonomy.ts";

export type TaskLearningMetadata = {
  templateId: string;
  topicId: TopicId;
  helpSectionId: HelpSectionId;
  skillId: string;
  focusLabel: string;
  shortHint: string;
  misconceptionIds?: string[];
};

export type MisconceptionMetadata = {
  id: string;
  label: string;
  helpSectionId: HelpSectionId;
  shortHint: string;
};

export const misconceptionMetadataById: Record<string, MisconceptionMetadata> = {
  "isoprocess-proportionality": {
    id: "isoprocess-proportionality",
    label: "выбирает неверный вид пропорциональности",
    helpSectionId: "gas-isoprocesses",
    shortHint: "Сначала назови постоянный параметр и только затем выбирай отношение.",
  },
  "solid-structure-from-appearance": {
    id: "solid-structure-from-appearance",
    label: "определяет строение только по внешнему виду",
    helpSectionId: "solid-structure",
    shortHint: "Опирайся на направление свойств и характер плавления, а не только на блеск или форму образца.",
  },
  "liquid-bulk-surface-confusion": {
    id: "liquid-bulk-surface-confusion",
    label: "смешивает текучесть объёма и силы поверхностного слоя",
    helpSectionId: "liquid-structure",
    shortHint: "Сначала реши, говорится о перестройке соседей в объёме или о нескомпенсированных силах на поверхности.",
  },
  "vapor-equilibrium-means-stillness": {
    id: "vapor-equilibrium-means-stillness",
    label: "принимает динамическое равновесие за остановку молекул",
    helpSectionId: "vapor-equilibrium",
    shortHint: "Постоянный уровень означает равенство встречных потоков, а не прекращение переходов через поверхность.",
  },
  "relative-humidity-wrong-denominator": {
    id: "relative-humidity-wrong-denominator",
    label: "сравнивает влажность без учёта температуры насыщения",
    helpSectionId: "air-humidity",
    shortHint: "Используй давление или плотность насыщенного пара именно при температуре воздуха в условии.",
  },
  "molecular-energy-celsius": {
    id: "molecular-energy-celsius",
    label: "подставляет градусы Цельсия вместо кельвинов",
    helpSectionId: "molecular-kinetic-energy",
    shortHint: "Сначала переведи температуру: T = t + 273.",
  },
  "particle-concentration-volume-unit": {
    id: "particle-concentration-volume-unit",
    label: "не переводит литры в кубические метры",
    helpSectionId: "particle-concentration",
    shortHint: "Перед вычислением концентрации переведи объём: 1 л = 10⁻³ м³.",
  },
  "molecule-count-skips-molar-mass": {
    id: "molecule-count-skips-molar-mass",
    label: "умножает массу прямо на постоянную Авогадро",
    helpSectionId: "amount-of-substance",
    shortHint: "Постоянная Авогадро относится к одному молю: сначала раздели массу на молярную массу.",
  },
  "uniform-motion-coordinate-sign": {
    id: "uniform-motion-coordinate-sign",
    label: "теряет знак проекции скорости",
    helpSectionId: "uniform-motion-graphs",
    shortHint: "В x = x₀ + vₓt проекция vₓ отрицательна при движении против выбранной оси.",
  },
  "uniform-motion-graph-reading": {
    id: "uniform-motion-graph-reading",
    label: "читает график без проверки осей",
    helpSectionId: "uniform-motion-graphs",
    shortHint: "На s(t) наклон показывает скорость; на v(t) высота линии показывает скорость.",
  },
  "vt-area-not-final-speed": {
    id: "vt-area-not-final-speed",
    label: "читает скорость как путь",
    helpSectionId: "motion-graphs",
    shortHint: "На v(t) знаковая площадь даёт перемещение; путь — сумма модулей площадей.",
  },
  "slope-vs-area": {
    id: "slope-vs-area",
    label: "путает наклон и площадь",
    helpSectionId: "motion-graphs",
    shortHint: "Наклон v(t) даёт ускорение, а знаковая площадь — перемещение.",
  },
  "forgot-acceleration-term": {
    id: "forgot-acceleration-term",
    label: "теряет член ускорения",
    helpSectionId: "accelerated-motion",
    shortHint: "При постоянном ускорении путь содержит член at²/2.",
  },
  "average-speed-arithmetic-mean": {
    id: "average-speed-arithmetic-mean",
    label: "усредняет скорости без учета времени",
    helpSectionId: "average-speed",
    shortHint: "Средняя путевая скорость равна всему пути, делённому на всё время.",
  },
  "projectile-axis-components": {
    id: "projectile-axis-components",
    label: "смешивает движения по двум осям",
    helpSectionId: "accelerated-motion",
    shortHint: "По x скорость постоянна; время полёта и высоту сначала находит вертикальная компонента v₀ᵧ.",
  },
  "average-speed-omits-stop": {
    id: "average-speed-omits-stop",
    label: "не включает остановку во всё время",
    helpSectionId: "average-speed",
    shortHint: "Пока тело стоит, путь не растёт, но общее время движения продолжается.",
  },
  "speed-unit-conversion": {
    id: "speed-unit-conversion",
    label: "не переводит скорость и время к одним единицам",
    helpSectionId: "units-conversion",
    shortHint: "Перед расчетом пути переведи км/ч в м/с, а минуты в секунды.",
  },
  "wrong-force-direction": {
    id: "wrong-force-direction",
    label: "складывает силы без направлений",
    helpSectionId: "resultant-force",
    shortHint: "Силы складываются как векторы: сначала ось и знаки, потом сумма.",
  },
  "friction-normal-force": {
    id: "friction-normal-force",
    label: "берет неверную реакцию опоры",
    helpSectionId: "friction",
    shortHint: "Трение равно μN; сначала найди N для конкретной опоры.",
  },
  "incline-projection-swap": {
    id: "incline-projection-swap",
    label: "путает sin и cos на наклонной",
    helpSectionId: "incline",
    shortHint: "Вдоль плоскости работает mg·sin α, поперёк — mg·cos α.",
  },
  "lift-acceleration-sign": {
    id: "lift-acceleration-sign",
    label: "выбирает знак по скорости лифта",
    helpSectionId: "weight-lift",
    shortHint: "Вес P и реакция N равны по модулю, но приложены к разным телам; знак задаёт ускорение.",
  },
  "impulse-resultant-force": {
    id: "impulse-resultant-force",
    label: "берёт импульс одной силы вместо равнодействующей",
    helpSectionId: "impulse-force",
    shortHint: "Изменение импульса задаёт импульс равнодействующей всех сил.",
  },
  "momentum-not-conserved": {
    id: "momentum-not-conserved",
    label: "не сохраняет импульс системы",
    helpSectionId: "momentum",
    shortHint: "Для сцепившихся тел сохраняется суммарный импульс до и после.",
  },
  "work-sign-error": {
    id: "work-sign-error",
    label: "не учитывает знак работы",
    helpSectionId: "work-energy",
    shortHint: "Работа отрицательна, если сила направлена против перемещения.",
  },
  "ohm-transform-error": {
    id: "ohm-transform-error",
    label: "ошибка в преобразовании закона Ома",
    helpSectionId: "ohms-law",
    shortHint: "Сначала вырази нужную величину из I = U/R, потом подставляй числа.",
  },
  "torque-arm-confusion": {
    id: "torque-arm-confusion",
    label: "путает плечо с расстоянием до точки приложения",
    helpSectionId: "torque-balance",
    shortHint: "Плечо силы — перпендикуляр от оси до линии действия силы.",
  },
  "wire-area-inverted": {
    id: "wire-area-inverted",
    label: "умножает сопротивление на площадь сечения",
    helpSectionId: "conductor-resistance",
    shortHint: "В $R=\\rho l/S$ площадь поперечного сечения стоит в знаменателе.",
  },
  "internal-resistance-missed": {
    id: "internal-resistance-missed",
    label: "теряет внутреннее сопротивление",
    helpSectionId: "full-circuit",
    shortHint: "В полной цепи ток ограничивает сумма внешнего и внутреннего сопротивлений.",
  },
  "charge-not-conserved": {
    id: "charge-not-conserved",
    label: "не сохраняет общий заряд",
    helpSectionId: "charge-sharing",
    shortHint: "Перед делением сложи заряды с учетом знаков.",
  },
  "capacitor-square-law": {
    id: "capacitor-square-law",
    label: "теряет квадрат напряжения",
    helpSectionId: "capacitor-energy",
    shortHint: "Энергия конденсатора пропорциональна U² и содержит множитель 1/2.",
  },
  "electric-power-voltage-only": {
    id: "electric-power-voltage-only",
    label: "находит напряжение вместо мощности",
    helpSectionId: "electric-power",
    shortHint: "После U=IR нужно еще найти P=UI или P=I²R.",
  },
  "temperature-celsius-kelvin": {
    id: "temperature-celsius-kelvin",
    label: "подставляет температуру в градусах Цельсия",
    helpSectionId: "gas-equation",
    shortHint: "В pV = νRT температура всегда в кельвинах.",
  },
  "heat-delta-temperature": {
    id: "heat-delta-temperature",
    label: "берет конечную температуру вместо изменения",
    helpSectionId: "heat-amount",
    shortHint: "В Q = cmΔT нужна разность температур.",
  },
  "heat-balance-arithmetic-mean": {
    id: "heat-balance-arithmetic-mean",
    label: "усредняет температуры без учета масс",
    helpSectionId: "heat-balance",
    shortHint: "В тепловом балансе массы задают вклад горячей и холодной воды.",
  },
  "elementary-charge-scale": {
    id: "elementary-charge-scale",
    label: "теряет масштаб элементарного заряда",
    helpSectionId: "elementary-charge",
    shortHint: "Одинаковый множитель 10⁻¹⁹ сокращается; раздели коэффициент заряда на 1,6.",
  },
  "fuel-specific-heat-missed": {
    id: "fuel-specific-heat-missed",
    label: "не учитывает массу топлива",
    helpSectionId: "fuel-combustion",
    shortHint: "Значение q относится к одному килограмму топлива; для массы m используй Q=qm.",
  },
  "melting-plateau-misread": {
    id: "melting-plateau-misread",
    label: "смешивает нагрев и плавление",
    helpSectionId: "heating-melting",
    shortHint: "Нагрев и плавление считаются разными стадиями и складываются.",
  },
  "vaporization-stage-omission": {
    id: "vaporization-stage-omission",
    label: "пропускает нагревание или парообразование",
    helpSectionId: "vaporization",
    shortHint: "Если вода начинает ниже 100 °C, отдельно посчитай нагревание и парообразование.",
  },
  "shadow-source-size": {
    id: "shadow-source-size",
    label: "не учитывает размер источника света",
    helpSectionId: "shadow-and-penumbra",
    shortHint: "Точечный источник даёт резкую границу; у протяжённого источника появляется область частичного освещения — полутень.",
  },
  "angle-from-surface": {
    id: "angle-from-surface",
    label: "отсчитывает углы от поверхности",
    helpSectionId: "reflection",
    shortHint: "Углы падения, отражения и преломления отсчитываются от нормали.",
  },
  "mirror-image-distance": {
    id: "mirror-image-distance",
    label: "путает расстояние до зеркала и до изображения",
    helpSectionId: "plane-mirror",
    shortHint: "Изображение за зеркалом на том же расстоянии: между предметом и изображением 2d.",
  },
  "refraction-density-direction": {
    id: "refraction-density-direction",
    label: "путает поворот луча при смене среды",
    helpSectionId: "refraction-direction",
    shortHint: "Из воздуха в воду луч отклоняется к нормали; из воды в воздух — от нормали.",
  },
  "refractive-index-inverted": {
    id: "refractive-index-inverted",
    label: "переворачивает отношение скоростей",
    helpSectionId: "refractive-index",
    shortHint: "В этих задачах n = c/v для обычной прозрачной среды в видимом свете, поэтому n > 1.",
  },
  "snell-without-sines": {
    id: "snell-without-sines",
    label: "делит углы вместо синусов",
    helpSectionId: "refraction",
    shortHint: "Закон преломления связывает синусы углов, а не сами углы.",
  },
  "lens-equation-sign": {
    id: "lens-equation-sign",
    label: "ошибается в знаменателе формулы линзы",
    helpSectionId: "thin-lens",
    shortHint: "Для действительного изображения f = F·d/(d − F): в знаменателе разность.",
  },
  "diopter-unit-conversion": {
    id: "diopter-unit-conversion",
    label: "не переводит фокусное расстояние в метры",
    helpSectionId: "optical-power",
    shortHint: "Диоптрия — это 1/м: сначала переведи F в метры.",
  },
  "magnification-inverted": {
    id: "magnification-inverted",
    label: "переворачивает отношение расстояний",
    helpSectionId: "magnification",
    shortHint: "Увеличение равно f/d — расстояние до изображения в числителе.",
  },
  "lens-image-kind": {
    id: "lens-image-kind",
    label: "путает действительное и мнимое изображение",
    helpSectionId: "lens-image-properties",
    shortHint: "Экран ловит изображение только там, где пересекаются сами лучи; пересечение продолжений даёт мнимое изображение.",
  },
  "vision-correction-sign": {
    id: "vision-correction-sign",
    label: "путает знак корректирующей линзы",
    helpSectionId: "vision-correction",
    shortHint: "Если фокус перед сетчаткой, его сдвигают назад рассеивающей линзой; если за сетчаткой — вперёд собирающей.",
  },
};

export const taskLearningMetadataByTemplateId: Record<string, TaskLearningMetadata> = {
  "archimedes-force": {
    templateId: "archimedes-force",
    topicId: "dynamics",
    helpSectionId: "archimedes-force",
    skillId: "archimedes-force",
    focusLabel: "Сила Архимеда",
    shortHint: "Переведи погружённый объём в м³, затем умножь плотность среды, g и этот объём.",
  },
  "ship-payload": {
    templateId: "ship-payload",
    topicId: "dynamics",
    helpSectionId: "ship-payload",
    skillId: "ship-payload",
    focusLabel: "Грузоподъёмность судна",
    shortHint: "Вычти массу судна без груза из водоизмещения при предельной осадке.",
  },
  "contact-pressure":{templateId:"contact-pressure",topicId:"dynamics",helpSectionId:"contact-pressure",skillId:"contact-pressure",focusLabel:"Давление на опору",shortHint:"Вырази искомую величину из p=F/S: F — полная сила, S — общая площадь контакта. Согласуй Па, Н и м²."},
  "free-fall": {
    templateId: "free-fall",
    topicId: "kinematics",
    helpSectionId: "accelerated-motion",
    skillId: "free-fall",
    focusLabel: "Свободное падение",
    shortHint: "Свободное падение из покоя — равноускоренное движение с ускорением g.",
    misconceptionIds: ["forgot-acceleration-term"],
  },
  "vt-slope": {
    templateId: "vt-slope",
    topicId: "kinematics",
    helpSectionId: "motion-graphs",
    skillId: "vt-slope",
    focusLabel: "Наклон графика v(t)",
    shortHint: "Наклон v(t) показывает ускорение на выбранном участке.",
    misconceptionIds: ["slope-vs-area"],
  },
  "vt-area": {
    templateId: "vt-area",
    topicId: "kinematics",
    helpSectionId: "motion-graphs",
    skillId: "vt-area",
    focusLabel: "Площадь под графиком v(t)",
    shortHint: "Площадь под v(t) показывает перемещение за весь интервал.",
    misconceptionIds: ["vt-area-not-final-speed", "slope-vs-area"],
  },
  "relative-velocity-vectors": {
    templateId: "relative-velocity-vectors",
    topicId: "kinematics",
    helpSectionId: "vectors-relative-motion",
    skillId: "relative-velocity-vectors",
    focusLabel: "Относительная скорость",
    shortHint: "Найди скорость тела относительно другого тела. Учитывай не только значения скоростей, но и их направления.",
  },
  "average-speed-segments": {
    templateId: "average-speed-segments",
    topicId: "kinematics",
    helpSectionId: "average-speed",
    skillId: "average-speed-segments",
    focusLabel: "Средняя путевая скорость",
    shortHint: "Считай среднюю путевую скорость через весь путь и всё время движения.",
    misconceptionIds: ["average-speed-arithmetic-mean"],
  },
  "projectile-components": {
    templateId: "projectile-components",
    topicId: "kinematics",
    helpSectionId: "accelerated-motion",
    skillId: "projectile-components",
    focusLabel: "Бросок под углом по компонентам",
    shortHint: "Раздели скорость на v₀ₓ и v₀ᵧ: вертикаль задаёт время, горизонталь — дальность за это время.",
    misconceptionIds: ["projectile-axis-components"],
  },
  "rotation-frequency": {
    templateId: "rotation-frequency",
    topicId: "kinematics",
    helpSectionId: "circular-motion",
    skillId: "rotation-frequency",
    focusLabel: "Частота вращения",
    shortHint: "Частота показывает число полных оборотов за одну секунду.",
  },
  "centripetal-acceleration": {
    templateId: "centripetal-acceleration",
    topicId: "kinematics",
    helpSectionId: "circular-motion",
    skillId: "centripetal-acceleration",
    focusLabel: "Центростремительное ускорение",
    shortHint: "Ускорение направлено к центру, а модуль равен a = v²/R.",
  },
  "average-speed-with-stop": {
    templateId: "average-speed-with-stop",
    topicId: "kinematics",
    helpSectionId: "average-speed",
    skillId: "average-speed-with-stop",
    focusLabel: "Средняя скорость с остановкой",
    shortHint: "Сложи весь путь и всё время, включая остановку.",
    misconceptionIds: ["average-speed-omits-stop", "average-speed-arithmetic-mean"],
  },
  "uniform-motion-basic": {
    templateId: "uniform-motion-basic",
    topicId: "kinematics",
    helpSectionId: "uniform-motion",
    skillId: "uniform-motion-basic",
    focusLabel: "Путь, скорость и время",
    shortHint: "Назови неизвестную величину и вырази её из связи s = vt.",
  },
  "uniform-coordinate-law": {
    templateId: "uniform-coordinate-law",
    topicId: "kinematics",
    helpSectionId: "uniform-motion-graphs",
    skillId: "uniform-coordinate-law",
    focusLabel: "Координата и знак скорости",
    shortHint: "Выбери направление оси и сохрани знак vₓ в формуле x = x₀ + vₓt.",
    misconceptionIds: ["uniform-motion-coordinate-sign"],
  },
  "uniform-motion-graphs": {
    templateId: "uniform-motion-graphs",
    topicId: "kinematics",
    helpSectionId: "uniform-motion-graphs",
    skillId: "uniform-motion-graphs",
    focusLabel: "Графики s(t) и v(t)",
    shortHint: "Прочитай подписи осей, затем определи, что показывает наклон или высота линии.",
    misconceptionIds: ["uniform-motion-graph-reading"],
  },
  "unit-conversion-speed": {
    templateId: "unit-conversion-speed",
    topicId: "kinematics",
    helpSectionId: "units-conversion",
    skillId: "unit-conversion-speed",
    focusLabel: "Перевод скорости",
    shortHint: "Перед расчетом пути переведи км/ч в м/с, а минуты в секунды.",
    misconceptionIds: ["speed-unit-conversion"],
  },
  "gravity-force": {
    templateId: "gravity-force",
    topicId: "dynamics",
    helpSectionId: "gravity-force",
    skillId: "gravity-force",
    focusLabel: "Сила тяжести и масса",
    shortHint: "Сила тяжести равна массе, умноженной на g; ответ записывают в ньютонах.",
  },
  "gravitation-distance": {
    templateId: "gravitation-distance",
    topicId: "dynamics",
    helpSectionId: "gravitation-distance",
    skillId: "gravitation-distance",
    focusLabel: "Квадрат расстояния в законе тяготения",
    shortHint: "Возведи коэффициент изменения расстояния в квадрат; сила изменится во столько раз в противоположную сторону.",
  },
  "hydrostatic-pressure": {templateId:"hydrostatic-pressure",topicId:"dynamics",helpSectionId:"hydrostatic-pressure",skillId:"hydrostatic-pressure",focusLabel:"Давление жидкости на глубине",shortHint:"Умножь плотность на g и глубину, затем переведи паскали в килопаскали."},
  "newton-second": {
    templateId: "newton-second",
    topicId: "dynamics",
    helpSectionId: "newton-second-law",
    skillId: "newton-second",
    focusLabel: "Второй закон Ньютона",
    shortHint: "Сравни все силы и найди ту, что остаётся: она вместе с массой задаёт ускорение.",
    misconceptionIds: ["wrong-force-direction"],
  },
  "friction-force": {
    templateId: "friction-force",
    topicId: "dynamics",
    helpSectionId: "friction",
    skillId: "friction-force",
    focusLabel: "Сила трения",
    shortHint: "Трение равно μN; сначала найди реакцию опоры.",
    misconceptionIds: ["friction-normal-force"],
  },
  "incline-force": {
    templateId: "incline-force",
    topicId: "dynamics",
    helpSectionId: "incline",
    skillId: "incline-force",
    focusLabel: "Наклонная плоскость",
    shortHint: "Разложи mg вдоль плоскости и перпендикулярно ей.",
    misconceptionIds: ["incline-projection-swap", "friction-normal-force"],
  },
  "resultant-force": {
    templateId: "resultant-force",
    topicId: "dynamics",
    helpSectionId: "resultant-force",
    skillId: "resultant-force",
    focusLabel: "Равнодействующая сил",
    shortHint: "Сначала отметь направления: силы навстречу гасят друг друга, силы в одну сторону складываются.",
    misconceptionIds: ["wrong-force-direction"],
  },
  "resultant-force-2d": {
    templateId: "resultant-force-2d",
    topicId: "dynamics",
    helpSectionId: "resultant-force",
    skillId: "resultant-force-2d",
    focusLabel: "Равнодействующая перпендикулярных сил",
    shortHint: "Перпендикулярные силы складываются по теореме Пифагора.",
    misconceptionIds: ["wrong-force-direction"],
  },
  "weight-lift": {
    templateId: "weight-lift",
    topicId: "dynamics",
    helpSectionId: "weight-lift",
    skillId: "weight-lift",
    focusLabel: "Вес тела в лифте",
    shortHint: "Вес P и реакция N равны по модулю при контакте; знак зависит от ускорения опоры.",
    misconceptionIds: ["lift-acceleration-sign"],
  },
  "inelastic-collision-speed": {
    templateId: "inelastic-collision-speed",
    topicId: "dynamics",
    helpSectionId: "momentum",
    skillId: "inelastic-collision-speed",
    focusLabel: "Неупругое столкновение",
    shortHint: "После сцепления тел общий импульс делится на общую массу.",
    misconceptionIds: ["momentum-not-conserved"],
  },
  "kinetic-energy": {
    templateId: "kinetic-energy",
    topicId: "dynamics",
    helpSectionId: "kinetic-energy",
    skillId: "kinetic-energy",
    focusLabel: "Кинетическая энергия",
    shortHint: "Кинетическая энергия зависит от квадрата скорости.",
  },
  "torque-balance": {
    templateId: "torque-balance",
    topicId: "dynamics",
    helpSectionId: "torque-balance",
    skillId: "torque-balance",
    focusLabel: "Равновесие моментов сил",
    shortHint: "Сравни произведения каждой силы на её перпендикулярное плечо.",
    misconceptionIds: ["torque-arm-confusion"],
  },
  "movable-pulley": {
    templateId: "movable-pulley",
    topicId: "dynamics",
    helpSectionId: "movable-pulley",
    skillId: "movable-pulley",
    focusLabel: "Выигрыш в силе подвижного блока",
    shortHint: "Две несущие ветви делят вес груза поровну.",
  },
  "gravitational-potential-energy": {
    templateId: "gravitational-potential-energy",
    topicId: "dynamics",
    helpSectionId: "potential-energy",
    skillId: "gravitational-potential-energy",
    focusLabel: "Потенциальная энергия",
    shortHint: "Высоту отсчитывай от указанного нулевого уровня: Eₚ = mgh.",
  },
  "mechanical-energy-conservation": {
    templateId: "mechanical-energy-conservation",
    topicId: "dynamics",
    helpSectionId: "energy-conservation",
    skillId: "mechanical-energy-conservation",
    focusLabel: "Сохранение механической энергии",
    shortHint: "Без сопротивления сумма Eₖ + Eₚ остаётся постоянной.",
  },
  "density-volume-ratio": {
    templateId: "density-volume-ratio",
    topicId: "thermodynamics",
    helpSectionId: "density-volume",
    skillId: "density-volume-ratio",
    focusLabel: "Плотность и объём",
    shortHint: "Масса пропорциональна плотности и объёму, а не линейному размеру.",
  },
  "impulse-momentum": {
    templateId: "impulse-momentum",
    topicId: "dynamics",
    helpSectionId: "impulse-force",
    skillId: "impulse-momentum",
    focusLabel: "Импульс силы",
    shortHint: "Импульс равнодействующей всех сил равен изменению импульса тела.",
    misconceptionIds: ["impulse-resultant-force"],
  },
  "work-force-distance": {
    templateId: "work-force-distance",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "work-force-distance",
    focusLabel: "Работа силы",
    shortHint: "Смотри на направление силы относительно перемещения: знак работы меняется.",
    misconceptionIds: ["work-sign-error"],
  },
  "work-at-angle": {
    templateId: "work-at-angle",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "work-at-angle",
    focusLabel: "Работа силы под углом",
    shortHint: "Найди проекцию силы на направление перемещения и учти знак косинуса.",
  },
  "mechanical-power": {
    templateId: "mechanical-power",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "mechanical-power",
    focusLabel: "Механическая мощность",
    shortHint: "Мощность показывает работу за единицу времени: P = A/t.",
  },
  "mechanical-efficiency": {
    templateId: "mechanical-efficiency",
    topicId: "dynamics",
    helpSectionId: "work-energy",
    skillId: "mechanical-efficiency",
    focusLabel: "КПД механизма",
    shortHint: "КПД — доля полезной работы во всей совершённой работе.",
  },
  "ohm-law": {
    templateId: "ohm-law",
    topicId: "electrodynamics",
    helpSectionId: "ohms-law",
    skillId: "ohm-law",
    focusLabel: "Закон Ома",
    shortHint: "Свяжи ток, напряжение и сопротивление до подстановки чисел.",
    misconceptionIds: ["ohm-transform-error"],
  },
  "conductor-resistance": {
    templateId: "conductor-resistance",
    topicId: "electrodynamics",
    helpSectionId: "conductor-resistance",
    skillId: "conductor-resistance",
    focusLabel: "Сопротивление проводника",
    shortHint: "Согласуй единицы ρ, l и S, затем используй $R=\\rho l/S$.",
    misconceptionIds: ["wire-area-inverted"],
  },
  "resistor-network": {
    templateId: "resistor-network",
    topicId: "electrodynamics",
    helpSectionId: "ohms-law",
    skillId: "resistor-network",
    focusLabel: "Соединения резисторов",
    shortHint: "Сначала найди эквивалентное сопротивление, затем применяй закон Ома.",
    misconceptionIds: ["ohm-transform-error"],
  },
  "source-internal-resistance": {
    templateId: "source-internal-resistance",
    topicId: "electrodynamics",
    helpSectionId: "full-circuit",
    skillId: "source-internal-resistance",
    focusLabel: "Полная цепь",
    shortHint: "Во всей цепи учитывай внешнее и внутреннее сопротивление.",
    misconceptionIds: ["internal-resistance-missed"],
  },
  "capacitor-energy": {
    templateId: "capacitor-energy",
    topicId: "electrodynamics",
    helpSectionId: "capacitor-energy",
    skillId: "capacitor-energy",
    focusLabel: "Энергия конденсатора",
    shortHint: "Энергия конденсатора зависит от U² и множителя 1/2.",
    misconceptionIds: ["capacitor-square-law"],
  },
  "electric-power": {
    templateId: "electric-power",
    topicId: "electrodynamics",
    helpSectionId: "electric-power",
    skillId: "electric-power",
    focusLabel: "Мощность тока",
    shortHint: "Не останавливайся на U=IR: для мощности используй P=UI или P=I²R.",
    misconceptionIds: ["electric-power-voltage-only", "ohm-transform-error"],
  },
  "charge-sharing": {
    templateId: "charge-sharing",
    topicId: "electrodynamics",
    helpSectionId: "charge-sharing",
    skillId: "charge-sharing",
    focusLabel: "Деление заряда",
    shortHint: "После контакта одинаковых проводников общий заряд делится поровну.",
    misconceptionIds: ["charge-not-conserved"],
  },
  "ideal-gas-state": {
    templateId: "ideal-gas-state",
    topicId: "thermodynamics",
    helpSectionId: "gas-equation",
    skillId: "ideal-gas-state",
    focusLabel: "Уравнение состояния газа",
    shortHint: "В pV = νRT температура всегда в кельвинах.",
    misconceptionIds: ["temperature-celsius-kelvin"],
  },
  "gas-state-ratio": {
    templateId: "gas-state-ratio",
    topicId: "thermodynamics",
    helpSectionId: "gas-equation",
    skillId: "gas-state-ratio",
    focusLabel: "Связь параметров газа",
    shortHint: "Для одной массы газа используй pV/T = const и температуру в кельвинах.",
    misconceptionIds: ["temperature-celsius-kelvin"],
  },
  "heat-amount": {
    templateId: "heat-amount",
    topicId: "thermodynamics",
    helpSectionId: "heat-amount",
    skillId: "heat-amount",
    focusLabel: "Количество теплоты",
    shortHint: "Q = cmΔT даёт теплоту тела при постоянной c, без фазового перехода; учитывай условие о потерях.",
    misconceptionIds: ["heat-delta-temperature"],
  },
  "heat-balance-simple": {
    templateId: "heat-balance-simple",
    topicId: "thermodynamics",
    helpSectionId: "heat-balance",
    skillId: "heat-balance-simple",
    focusLabel: "Тепловой баланс",
    shortHint: "При смешивании отданная горячей водой теплота равна полученной холодной.",
    misconceptionIds: ["heat-balance-arithmetic-mean"],
  },
  "ideal-gas-isoprocess": {
    templateId: "ideal-gas-isoprocess",
    topicId: "thermodynamics",
    helpSectionId: "gas-isoprocesses",
    skillId: "ideal-gas-isoprocess",
    focusLabel: "Законы изопроцессов",
    shortHint: "Определи, что постоянно: T, p или V; затем выбери обратную или прямую пропорциональность.",
    misconceptionIds: ["isoprocess-proportionality"],
  },
  "solid-structure-properties": {
    templateId: "solid-structure-properties",
    topicId: "thermodynamics",
    helpSectionId: "solid-structure",
    skillId: "solid-structure-properties",
    focusLabel: "Строение твёрдых тел",
    shortHint: "Определи, что задано: единая решётка, множество зёрен или аморфное состояние.",
    misconceptionIds: ["solid-structure-from-appearance"],
  },
  "liquid-structure-properties": {
    templateId: "liquid-structure-properties",
    topicId: "thermodynamics",
    helpSectionId: "liquid-structure",
    skillId: "liquid-structure-properties",
    focusLabel: "Строение жидкостей",
    shortHint: "Раздели движение частиц в объёме и нескомпенсированные силы поверхностного слоя.",
    misconceptionIds: ["liquid-bulk-surface-confusion"],
  },
  "vapor-dynamic-equilibrium": {
    templateId: "vapor-dynamic-equilibrium",
    topicId: "thermodynamics",
    helpSectionId: "vapor-equilibrium",
    skillId: "vapor-dynamic-equilibrium",
    focusLabel: "Испарение и насыщенный пар",
    shortHint: "Сравни два встречных потока молекул за одинаковое время и проверь, закрыта ли система.",
    misconceptionIds: ["vapor-equilibrium-means-stillness"],
  },
  "relative-humidity-pressure": {
    templateId: "relative-humidity-pressure",
    topicId: "thermodynamics",
    helpSectionId: "air-humidity",
    skillId: "relative-humidity-pressure",
    focusLabel: "Относительная влажность воздуха",
    shortHint: "Раздели фактическое давление пара на давление насыщенного пара при той же температуре и вырази долю в процентах.",
    misconceptionIds: ["relative-humidity-wrong-denominator"],
  },
  "molecule-count-from-mass": {
    templateId: "molecule-count-from-mass",
    topicId: "thermodynamics",
    helpSectionId: "amount-of-substance",
    skillId: "molecule-count-from-mass",
    focusLabel: "Число молекул",
    shortHint: "Сначала найди количество вещества ν = m/M, затем умножь его на постоянную Авогадро.",
    misconceptionIds: ["molecule-count-skips-molar-mass"],
  },
  "particle-concentration": {
    templateId: "particle-concentration",
    topicId: "thermodynamics",
    helpSectionId: "particle-concentration",
    skillId: "particle-concentration",
    focusLabel: "Концентрация частиц",
    shortHint: "Переведи объём в кубические метры и раздели число частиц на этот объём.",
    misconceptionIds: ["particle-concentration-volume-unit"],
  },
  "molecular-kinetic-energy": {
    templateId: "molecular-kinetic-energy",
    topicId: "thermodynamics",
    helpSectionId: "molecular-kinetic-energy",
    skillId: "molecular-kinetic-energy",
    focusLabel: "Средняя энергия молекул",
    shortHint: "Переведи температуру в кельвины и используй среднюю энергию 3kT/2.",
    misconceptionIds: ["molecular-energy-celsius"],
  },
  "elementary-charge-count": {
    templateId: "elementary-charge-count",
    topicId: "electrodynamics",
    helpSectionId: "elementary-charge",
    skillId: "elementary-charge-count",
    focusLabel: "Число элементарных зарядов",
    shortHint: "Сравни модуль заряда с e = 1,6 · 10⁻¹⁹ Кл.",
    misconceptionIds: ["elementary-charge-scale"],
  },
  "magnetic-field-direction": {
    templateId: "magnetic-field-direction",
    topicId: "electrodynamics",
    helpSectionId: "magnetic-field",
    skillId: "magnetic-field-direction",
    focusLabel: "Направление магнитного поля",
    shortHint: "Сначала установи направление тока, затем примени правило правой руки; северный конец стрелки показывает направление поля.",
  },
  "fuel-combustion-heat": {
    templateId: "fuel-combustion-heat",
    topicId: "thermodynamics",
    helpSectionId: "fuel-combustion",
    skillId: "fuel-combustion-heat",
    focusLabel: "Теплота сгорания топлива",
    shortHint: "При полном сгорании умножь удельную теплоту сгорания на массу топлива.",
    misconceptionIds: ["fuel-specific-heat-missed"],
  },
  "phase-change-heat": {
    templateId: "phase-change-heat",
    topicId: "thermodynamics",
    helpSectionId: "heating-melting",
    skillId: "phase-change-heat",
    focusLabel: "Нагревание и плавление",
    shortHint: "Нагрев и плавление считаются отдельными стадиями и складываются.",
    misconceptionIds: ["melting-plateau-misread", "heat-delta-temperature"],
  },
  "vaporization-heat": {
    templateId: "vaporization-heat",
    topicId: "thermodynamics",
    helpSectionId: "vaporization",
    skillId: "vaporization-heat",
    focusLabel: "Нагревание и парообразование",
    shortHint: "Сначала нагрей воду до температуры кипения, затем прибавь теплоту парообразования.",
    misconceptionIds: ["vaporization-stage-omission", "heat-delta-temperature"],
  },
  "reflection-angle": {
    templateId: "reflection-angle",
    topicId: "optics",
    helpSectionId: "reflection",
    skillId: "reflection-angle",
    focusLabel: "Закон отражения",
    shortHint: "Угол отражения равен углу падения; оба отсчитываются от нормали.",
    misconceptionIds: ["angle-from-surface"],
  },
  "plane-mirror-separation": {
    templateId: "plane-mirror-separation",
    topicId: "optics",
    helpSectionId: "plane-mirror",
    skillId: "plane-mirror-separation",
    focusLabel: "Плоское зеркало",
    shortHint: "Между предметом и мнимым изображением — удвоенное расстояние до зеркала.",
    misconceptionIds: ["mirror-image-distance"],
  },
  "shadow-and-penumbra": {
    templateId: "shadow-and-penumbra",
    topicId: "optics",
    helpSectionId: "shadow-and-penumbra",
    skillId: "shadow-and-penumbra",
    focusLabel: "Тень и полутень",
    shortHint: "Определи, точечный источник или протяжённый, затем проследи граничные лучи до экрана.",
    misconceptionIds: ["shadow-source-size"],
  },
  "refraction-direction": {
    templateId: "refraction-direction",
    topicId: "optics",
    helpSectionId: "refraction-direction",
    skillId: "refraction-direction",
    focusLabel: "Направление преломлённого луча",
    shortHint: "Отметь нормаль и направление перехода: в воду луч поворачивает к нормали, из воды в воздух — от нормали.",
    misconceptionIds: ["refraction-density-direction"],
  },
  "refractive-index-speed": {
    templateId: "refractive-index-speed",
    topicId: "optics",
    helpSectionId: "refractive-index",
    skillId: "refractive-index-speed",
    focusLabel: "Показатель преломления",
    shortHint: "n = c/v: c дели на фазовую скорость света в обычной прозрачной среде.",
    misconceptionIds: ["refractive-index-inverted"],
  },
  "snell-index-ratio": {
    templateId: "snell-index-ratio",
    topicId: "optics",
    helpSectionId: "refraction",
    skillId: "snell-index-ratio",
    focusLabel: "Закон преломления",
    shortHint: "Отношение показателей равно отношению синусов углов от нормали.",
    misconceptionIds: ["snell-without-sines", "angle-from-surface"],
  },
  "thin-lens-image-distance": {
    templateId: "thin-lens-image-distance",
    topicId: "optics",
    helpSectionId: "thin-lens",
    skillId: "thin-lens-image-distance",
    focusLabel: "Формула тонкой линзы",
    shortHint: "Вырази f из 1/F = 1/d + 1/f, следи за разностью в знаменателе.",
    misconceptionIds: ["lens-equation-sign"],
  },
  "lens-optical-power": {
    templateId: "lens-optical-power",
    topicId: "optics",
    helpSectionId: "optical-power",
    skillId: "lens-optical-power",
    focusLabel: "Оптическая сила",
    shortHint: "Переведи фокусное расстояние в метры и возьми обратную величину.",
    misconceptionIds: ["diopter-unit-conversion"],
  },
  "lens-image-height": {
    templateId: "lens-image-height",
    topicId: "optics",
    helpSectionId: "magnification",
    skillId: "lens-image-height",
    focusLabel: "Увеличение линзы",
    shortHint: "Модуль увеличения dᵢ/dₒ умножь на высоту предмета h.",
    misconceptionIds: ["magnification-inverted"],
  },
  "lens-image-properties": {
    templateId: "lens-image-properties",
    topicId: "optics",
    helpSectionId: "lens-image-properties",
    skillId: "lens-image-properties",
    focusLabel: "Свойства изображения в линзе",
    shortHint: "Расположи предмет относительно F и 2F, затем проверь, пересекаются лучи или их продолжения.",
    misconceptionIds: ["lens-image-kind"],
  },
  "vision-correction": {
    templateId: "vision-correction",
    topicId: "optics",
    helpSectionId: "vision-correction",
    skillId: "vision-correction",
    focusLabel: "Коррекция зрения линзами",
    shortHint: "Сначала найди фокус относительно сетчатки, затем выбери знак и тип линзы.",
    misconceptionIds: ["vision-correction-sign"],
  },
};

export function getTaskLearningMetadata(templateId: string | undefined) {
  if (!templateId) {
    return undefined;
  }

  return taskLearningMetadataByTemplateId[templateId];
}

export function getMisconceptionMetadata(misconceptionId: string | undefined) {
  if (!misconceptionId) {
    return undefined;
  }

  return misconceptionMetadataById[misconceptionId];
}

