"use client";
import Image from "next/image";
import {useState} from "react";
import {MIO_SCENES} from "../../lib/learning/mio-assets";
import shared from "./TextbookScene.module.css";
import styles from "./SIUnitsModel.module.css";

const cases={length:{label:"Длина",symbol:"l",first:"2,5 м",second:"250 см",factor:"1 м = 100 см",note:"Число стало в 100 раз больше, потому что сантиметр в 100 раз меньше метра."},mass:{label:"Масса",symbol:"m",first:"1,2 кг",second:"1200 г",factor:"1 кг = 1000 г",note:"Физическая масса не изменилась. Изменилась единица и соответствующее ей число."},time:{label:"Время",symbol:"t",first:"1,5 ч",second:"5400 с",factor:"1 ч = 3600 с",note:"Полтора часа и 5400 секунд описывают один и тот же промежуток времени."}} as const;
type CaseId=keyof typeof cases;
export function SIUnitsModel(){const[id,setId]=useState<CaseId>("length");const item=cases[id];return <div className={shared.experiment}><div className={styles.heading}><div><p>Величина та же · запись другая</p><h2>Почему число изменилось?</h2></div><p>Мио записывает один результат в двух единицах. Равенство должно сохранять не только число, но и физическую величину.</p></div><div className={styles.workspace}><figure className={styles.scene}><Image src={MIO_SCENES.measurement} alt="Мио записывает результат измерения в согласованных единицах" fill sizes="(max-width:700px) 100vw, 690px" priority/><div className={styles.note}><span>{item.label}</span><strong>{item.symbol} = {item.first}</strong><b>= {item.second}</b></div><figcaption>Мио не измеряет объект заново: она переводит уже полученное значение в другую единицу.</figcaption></figure><div className={styles.panel}><div className={styles.choices} role="group" aria-label="Величина для перевода единиц">{(Object.keys(cases) as CaseId[]).map(key=><button key={key} type="button" aria-pressed={id===key} onClick={()=>setId(key)}>{cases[key].label}</button>)}</div><section className={styles.result} aria-live="polite"><p>Связь единиц</p><strong>{item.factor}</strong><span>{item.note}</span></section><p className={styles.rule}><b>Проверка смысла:</b> более мелкой единице соответствует большее числовое значение той же величины.</p></div></div></div>}
